/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.auth.jsonc --include-runtime=false --env-interface=AppsHostTrustedBindings worker-configuration.auth.d.ts` (hash: 353ca331dcc385f8aa066a86f6c376f8)
interface __BaseEnv_AppsHostTrustedBindings {
	STELLA_DEPLOYMENT_IDENTITY: "preview:basic-nightingale-118" | "dev:outgoing-bulldog-865";
	HOST_ROLE: "trusted";
	SHARES_DISABLED: "false";
	CONVEX_SITE_URL: "https://basic-nightingale-118.convex.site" | "https://outgoing-bulldog-865.convex.site";
	CONVEX_CLOUD_URL: "https://basic-nightingale-118.convex.cloud" | "https://outgoing-bulldog-865.convex.cloud";
	APPS_HOST_ORIGIN: "https://stella-v2-apps-host-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-apps-host-dev.lolruuxi.workers.dev";
	TRUSTED_APPS_HOST_ORIGIN: "https://stella-v2-apps-auth-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-apps-auth-dev.lolruuxi.workers.dev";
	CLOUD_BUILDER_ORIGIN: "https://stella-v2-cloud-builder-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-cloud-builder-dev.lolruuxi.workers.dev";
	BUILDER_SERVICE_SECRET: string;
	APP_TOKEN_SIGNING_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Bn118Env {
		STELLA_DEPLOYMENT_IDENTITY: "preview:basic-nightingale-118";
		HOST_ROLE: "trusted";
		SHARES_DISABLED: "false";
		CONVEX_SITE_URL: "https://basic-nightingale-118.convex.site";
		CONVEX_CLOUD_URL: "https://basic-nightingale-118.convex.cloud";
		APPS_HOST_ORIGIN: "https://stella-v2-apps-host-basic-nightingale-118.lolruuxi.workers.dev";
		TRUSTED_APPS_HOST_ORIGIN: "https://stella-v2-apps-auth-basic-nightingale-118.lolruuxi.workers.dev";
		CLOUD_BUILDER_ORIGIN: "https://stella-v2-cloud-builder-basic-nightingale-118.lolruuxi.workers.dev";
		BUILDER_SERVICE_SECRET: string;
		APP_TOKEN_SIGNING_KEY: string;
	}
	interface Env extends __BaseEnv_AppsHostTrustedBindings {}
}
interface AppsHostTrustedBindings extends __BaseEnv_AppsHostTrustedBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STELLA_DEPLOYMENT_IDENTITY" | "HOST_ROLE" | "SHARES_DISABLED" | "CONVEX_SITE_URL" | "CONVEX_CLOUD_URL" | "APPS_HOST_ORIGIN" | "TRUSTED_APPS_HOST_ORIGIN" | "CLOUD_BUILDER_ORIGIN" | "BUILDER_SERVICE_SECRET" | "APP_TOKEN_SIGNING_KEY">> {}
}
