/**
 * Expo config plugin — wires Stella's CarPlay scene into the iOS project.
 *
 * This is a Continuous Native Generation (CNG) app: `ios/` is gitignored and
 * regenerated by `expo prebuild` (and by EAS Build), so all native CarPlay
 * wiring lives here rather than in a hand-edited Xcode project.
 *
 * Why a TWO-scene migration (and why a CarPlay-only manifest black-screens):
 *   `react-native-carplay` needs a `CPTemplateApplicationSceneSessionRole-
 *   Application` scene in `UIApplicationSceneManifest`. But the moment a
 *   manifest declares `UIApplicationSupportsMultipleScenes: true` + a
 *   `UISceneConfigurations` dict, iOS treats the WHOLE app as scene-based and
 *   stops presenting the AppDelegate's window automatically. This Expo SDK 55
 *   project uses the window-based Swift AppDelegate
 *   (`window = UIWindow(...); factory.startReactNative(in: window)`), so a
 *   CarPlay-only manifest (no phone window scene) orphans that window and the
 *   phone launches to a black screen — even though the JS bundle is fine.
 *
 * Fix (the documented multi-scene react-native-carplay pattern, adapted to
 * Expo's AppDelegate):
 *   1. Declare BOTH scene roles in `UIApplicationSceneManifest`:
 *        - `UIWindowSceneSessionRoleApplication`  -> StellaPhoneSceneDelegate
 *        - `CPTemplateApplicationSceneSessionRoleApplication` -> StellaCarSceneDelegate
 *   2. `StellaPhoneSceneDelegate` (Swift) re-parents the window the AppDelegate
 *      already created (with RN started in it) onto the connecting UIWindow-
 *      Scene, so the phone app launches normally under scene lifecycle.
 *   3. `StellaCarSceneDelegate` (Obj-C) immediately installs a tiny native
 *      CPListTemplate placeholder, then hands the CarPlay interface controller
 *      to react-native-carplay's `RNCarPlay`, so the JS template controller
 *      (src/carplay) can replace the placeholder on connect. The placeholder
 *      keeps a real head unit from displaying a permanent blank surface when
 *      JS/RN event delivery races CarPlay scene connection.
 *   4. Both delegate sources are registered in the Xcode Sources build phase.
 *
 * Entitlement: a real CarPlay head unit requires Apple to grant
 * `com.apple.developer.carplay-audio` (Audio category). Stella declares it in
 * app.json; keep the EAS provisioning profile carrying the same entitlement.
 * The iOS CarPlay Simulator does not enforce entitlements, so simulator success
 * is not proof that a TestFlight IPA is signed with the key.
 */

const {
  withInfoPlist,
  withDangerousMod,
  withXcodeProject,
  IOSConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const CAR_DELEGATE = "StellaCarSceneDelegate";
const CAR_SCENE_CONFIG_NAME = "Stella-CarPlay";
const PHONE_DELEGATE = "StellaPhoneSceneDelegate";
const PHONE_SCENE_CONFIG_NAME = "Stella-Phone";

const CARPLAY_SCENE_ROLE = "CPTemplateApplicationSceneSessionRoleApplication";
const PHONE_SCENE_ROLE = "UIWindowSceneSessionRoleApplication";

const CAR_HEADER_CONTENTS = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
#import <UIKit/UIKit.h>
#import <CarPlay/CarPlay.h>

@interface ${CAR_DELEGATE} : UIResponder <CPTemplateApplicationSceneDelegate>
@end
`;

// The CarPlay scene delegate MUST implement the modern (iOS 14+) no-window
// connect selector `templateApplicationScene:didConnectInterfaceController:`.
// On a real head unit (iOS 26.5, build 86), CarPlay's
// `-[CPTemplateApplicationScene _deliverInterfaceControllerToDelegate]`
// dispatches to that selector; when the delegate implements only the legacy
// iOS-13 `...didConnectInterfaceController:toWindow:` variant, CarPlay treats
// the delegate as not implementing the required connect method and raises an
// UNCAUGHT NSException at scene-connect — before any RN/JS runs — which aborts
// the app (SIGABRT). This matches react-native-carplay's own documented scene
// delegate. We obtain the CarPlay window from `templateApplicationScene.carWindow`
// (non-null on connect) and keep the legacy window variants as harmless
// fallbacks (deployment target is iOS 15.1, so the modern selectors always win,
// but the fallbacks cost nothing and cover any edge).
const CAR_IMPL_CONTENTS = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
#import "${CAR_DELEGATE}.h"
#import "RNCarPlay.h"

static NSString * const StellaCarPlayDiagnosticsKey = @"StellaCarPlayDiagnostics";

static void StellaCarPlayLog(NSString *format, ...) {
  va_list args;
  va_start(args, format);
  NSString *message = [[NSString alloc] initWithFormat:format arguments:args];
  va_end(args);

  NSLog(@"[carplay] %@", message);

  NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
  NSArray<NSString *> *existing = [defaults stringArrayForKey:StellaCarPlayDiagnosticsKey] ?: @[];
  NSMutableArray<NSString *> *next = [existing mutableCopy];
  NSString *line = [NSString stringWithFormat:@"%@ %@", [NSDate date], message];
  [next addObject:line];
  while (next.count > 80) {
    [next removeObjectAtIndex:0];
  }
  [defaults setObject:next forKey:StellaCarPlayDiagnosticsKey];
  [defaults synchronize];
}

static void StellaCarPlayInstallPlaceholder(CPInterfaceController *interfaceController) {
  if (!interfaceController) {
    StellaCarPlayLog(@"missing CPInterfaceController; cannot install native placeholder");
    return;
  }

  CPListItem *talkItem = [[CPListItem alloc] initWithText:@"Talk to Stella"
                                               detailText:@"Starting voice mode..."
                                                    image:nil
                                 showsDisclosureIndicator:NO];
  CPListSection *section = [[CPListSection alloc] initWithItems:@[talkItem]
                                                        header:nil
                                             sectionIndexTitle:nil];
  CPListTemplate *template = [[CPListTemplate alloc] initWithTitle:@"Stella" sections:@[section]];

  [interfaceController setRootTemplate:template animated:NO completion:^(BOOL done, NSError * _Nullable error) {
    StellaCarPlayLog(@"native placeholder setRootTemplate done=%@ error=%@",
                     done ? @"YES" : @"NO",
                     error.localizedDescription ?: @"none");
  }];
}

@implementation ${CAR_DELEGATE}

// iOS 14+ (current) — the selector CarPlay dispatches to on modern iOS.
- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
   didConnectInterfaceController:(CPInterfaceController *)interfaceController {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didConnect modern selector window=%@ bounds=%@",
                     templateApplicationScene.carWindow ? @"YES" : @"NO",
                     templateApplicationScene.carWindow ? NSStringFromCGRect(templateApplicationScene.carWindow.bounds) : @"nil");
    StellaCarPlayInstallPlaceholder(interfaceController);
    [RNCarPlay connectWithInterfaceController:interfaceController
                                      window:templateApplicationScene.carWindow];
    StellaCarPlayLog(@"forwarded connect to RNCarPlay");
  });
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
didDisconnectInterfaceController:(CPInterfaceController *)interfaceController {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didDisconnect modern selector");
    [RNCarPlay disconnect];
  });
}

// iOS 13 fallbacks — never selected on iOS 14+, kept for completeness.
- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
   didConnectInterfaceController:(CPInterfaceController *)interfaceController
                        toWindow:(CPWindow *)window {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didConnect legacy selector window=%@ bounds=%@",
                     window ? @"YES" : @"NO",
                     window ? NSStringFromCGRect(window.bounds) : @"nil");
    StellaCarPlayInstallPlaceholder(interfaceController);
    [RNCarPlay connectWithInterfaceController:interfaceController window:window];
    StellaCarPlayLog(@"forwarded legacy connect to RNCarPlay");
  });
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
didDisconnectInterfaceController:(CPInterfaceController *)interfaceController
                      fromWindow:(CPWindow *)window {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didDisconnect legacy selector");
    [RNCarPlay disconnect];
  });
}

@end
`;

// The phone scene delegate adopts the window the Expo AppDelegate already
// created in `didFinishLaunchingWithOptions` (React Native is started into it
// there). We only re-parent that window onto the connecting UIWindowScene so it
// becomes the app's foreground scene — no RN re-host, so the phone app behaves
// exactly as before, just under scene lifecycle. `@objc(StellaPhoneSceneDelegate)`
// exposes the class under the bare name the Info.plist references.
const PHONE_DELEGATE_SWIFT = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
import UIKit

@objc(${PHONE_DELEGATE})
class ${PHONE_DELEGATE}: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = UIApplication.shared.delegate,
          let appWindow = appDelegate.window,
          let window = appWindow
    else { return }
    window.windowScene = windowScene
    self.window = window
    window.makeKeyAndVisible()
  }

  // Forward universal links opened via the scene to the existing AppDelegate
  // continue-userActivity path (RCTLinkingManager) so deep links keep working.
  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    UIApplication.shared.delegate?.application?(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }
}
`;

const withCarPlaySceneManifest = (config) =>
  withInfoPlist(config, (cfg) => {
    const existing =
      cfg.modResults.UIApplicationSceneManifest &&
      typeof cfg.modResults.UIApplicationSceneManifest === "object"
        ? cfg.modResults.UIApplicationSceneManifest
        : {};
    const existingConfigs =
      existing.UISceneConfigurations &&
      typeof existing.UISceneConfigurations === "object"
        ? existing.UISceneConfigurations
        : {};

    cfg.modResults.UIApplicationSceneManifest = {
      ...existing,
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        ...existingConfigs,
        [PHONE_SCENE_ROLE]: [
          {
            UISceneClassName: "UIWindowScene",
            UISceneConfigurationName: PHONE_SCENE_CONFIG_NAME,
            UISceneDelegateClassName: PHONE_DELEGATE,
          },
        ],
        [CARPLAY_SCENE_ROLE]: [
          {
            UISceneClassName: "CPTemplateApplicationScene",
            UISceneConfigurationName: CAR_SCENE_CONFIG_NAME,
            UISceneDelegateClassName: CAR_DELEGATE,
          },
        ],
      },
    };
    return cfg;
  });

const withSceneDelegateSources = (config) =>
  withDangerousMod(config, [
    "ios",
    (cfg) => {
      const appName = cfg.modRequest.projectName;
      const dir = path.join(cfg.modRequest.platformProjectRoot, appName);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${CAR_DELEGATE}.h`), CAR_HEADER_CONTENTS);
      fs.writeFileSync(path.join(dir, `${CAR_DELEGATE}.m`), CAR_IMPL_CONTENTS);
      fs.writeFileSync(
        path.join(dir, `${PHONE_DELEGATE}.swift`),
        PHONE_DELEGATE_SWIFT,
      );
      return cfg;
    },
  ]);

const withSceneDelegateBuildFiles = (config) =>
  withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const appName = cfg.modRequest.projectName;
    // Idempotent: prebuild may run twice against the same project.
    for (const rel of [
      `${appName}/${CAR_DELEGATE}.m`,
      `${appName}/${PHONE_DELEGATE}.swift`,
    ]) {
      if (!project.hasFile(rel)) {
        IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
          filepath: rel,
          groupName: appName,
          project,
        });
      }
    }
    return cfg;
  });

/** @param {import('@expo/config-plugins').ExpoConfig} config */
module.exports = function withStellaCarPlay(config) {
  config = withCarPlaySceneManifest(config);
  config = withSceneDelegateSources(config);
  config = withSceneDelegateBuildFiles(config);
  return config;
};
