[package]
name = "stella-runtime-worker"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
worker = { git = "https://github.com/cloudflare/workers-rs", rev = "b57ba6ef8198c65499c2f92b1845cc2412dd6e8c", features = ["experimental_tokio"] }
stella-runtime-core = { path = "../../packages/runtime-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", default-features = false, features = ["rt", "macros", "sync", "time"] }

[profile.release]
opt-level = "s"

[patch."https://github.com/guybedford/libc"]
libc = { git = "https://github.com/rust-lang/libc", branch = "libc-0.2" }

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", branch = "libc-0.2" }
tokio = { git = "https://github.com/guybedford/tokio", tag = "1.53.1-cf.emscripten" }
tokio-macros = { git = "https://github.com/guybedford/tokio", tag = "1.53.1-cf.emscripten" }
mio = { git = "https://github.com/guybedford/mio", tag = "1.2.3-cf.emscripten" }
