name = "stella-v2-runtime-rust-dev"
main = "build/index.js"
compatibility_date = "2026-09-28"
compatibility_flags = ["new_module_registry"]

[build]
command = "node toolchain/build.mjs"

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "RuntimeSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RuntimeSession"]
