import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { setupEnvironment } from "dugite";
import type {
  SelfModFeatureSnapshot,
  StoreInstallRecord,
} from "../../contracts/index.js";
import { StoreModStore } from "../storage/store-mod-store.js";
import { commitGitMessage, getStagedDiffPreview } from "./git/commit.js";
import {
  getGitCommitParent,
  getGitHeadCommitSequence,
  listGitDirtyFiles,
  listRecentGitCommits,
} from "./git/log.js";
import { revertGitCommits } from "./git/revert.js";
import { sanitizeStellaTrailerValue } from "./git/trailers.js";
import { buildStellaSourceChangeSetForGitCommit } from "./stella-source-history.js";
import type {
  StellaSourceRevisionOrigin,
  StellaSourceHistoryStore,
} from "../storage/stella-source-history-store.js";

const execFileAsync = promisify(execFile);

export type CommitMessageProviderArgs = {
  /** What the agent was asked to do (subagent task description). */
  taskDescription: string;
  /** Files about to be committed (relative repo paths). */
  files: string[];
  /** Truncated unified diff of staged changes (may be empty). */
  diffPreview: string;
  /** Conversation that produced these changes; used as a context hint. */
  conversationId?: string;
};

/**
 * Provider for the agent-authored commit subject. Returning `null` (or
 * an empty string) falls back to the run's task description.
 */
export type CommitMessageProvider = (
  args: CommitMessageProviderArgs,
) => Promise<string | null>;

/**
 * Provider for the rolling-window feature namer. Receives the most
 * recent self-mod commits (excluding the repo's first-ever commit) plus
 * the previous snapshot items, and returns a normie-friendly grouped
 * list of names. Returning `null` leaves the previous snapshot in place.
 */
export type FeatureNamerProvider = (args: {
  commits: Array<{
    commitHash: string;
    shortHash: string;
    subject: string;
    body: string;
    timestampMs: number;
    files: string[];
  }>;
  /**
   * The currently-displayed snapshot items. The namer should keep these
   * names stable for groups whose commits did not change, instead of
   * re-deriving every label from scratch on each commit.
   */
  previousItems: SelfModFeatureSnapshot["items"];
}) => Promise<SelfModFeatureSnapshot["items"] | null>;

type SelfModApplyMode =
  | "author"
  | "install"
  | "update"
  | "uninstall"
  | "desktop-update";

type ActiveSelfModRun = {
  baselineDirtyFiles: Set<string>;
  taskDescription: string;
  packageId?: string;
  releaseNumber?: number;
  applyMode: SelfModApplyMode;
};

export type FinalizedSelfModCommit = {
  commitHash: string;
  files: string[];
  /**
   * Files left out of the commit: dirty before the run started (user
   * work), or currently owned by another still-active self-mod run
   * (concurrent-run attribution).
   */
  blockedFiles: string[];
  /**
   * Present for store/update apply modes, where the install ledger needs
   * it synchronously. Author-mode runs record source history in the
   * background (off the apply critical path) and omit it here.
   */
  sourceRevisionId?: string;
};

const ROLLING_WINDOW_SIZE = 10;

const normalizeFileList = (files: string[]): string[] =>
  Array.from(
    new Set(
      files.map((file) => file.trim().replace(/\\/g, "/")).filter(Boolean),
    ),
  ).sort();

const trimOrUndefined = (value: string | undefined): string | undefined => {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
};

const normalizeReleaseNumber = (
  value: number | undefined,
): number | undefined =>
  typeof value === "number" && Number.isFinite(value)
    ? Math.max(1, Math.floor(value))
    : undefined;

const sanitizeTrailerOrWarn = (
  value: string | undefined,
  trailerName: string,
): string | undefined => {
  const sanitized = sanitizeStellaTrailerValue(value);
  if (value?.trim() && !sanitized) {
    // A dropped trailer silently degrades revert-notice routing to
    // orchestrator-only. Surface it so a new caller with an unexpected
    // key shape fails loudly instead of mysteriously mis-routing undos.
    console.warn(
      `[self-mod] Dropping invalid ${trailerName} trailer value: ${JSON.stringify(value)}`,
    );
  }
  return sanitized;
};

/**
 * Owns the self-mod commit lifecycle and the install ledger. Per-commit
 * grouping/feature-roster stuff is gone — the side panel reads a
 * rolling-window snapshot regenerated by the cheap-LLM namer after each
 * commit.
 */
export class StoreModService {
  private readonly activeRuns = new Map<string, ActiveSelfModRun>();
  private firstRepoCommit: string | null | undefined = undefined;
  /**
   * Serialized queue for post-commit background work (source-history
   * recording + feature-snapshot regeneration). Chained so revisions
   * record in commit order — parent-revision lookup depends on the
   * previous commit's revision already existing.
   */
  private backgroundQueue: Promise<void> = Promise.resolve();

  constructor(
    private readonly repoRoot: string,
    private readonly store: StoreModStore,
    private readonly sourceHistory?: StellaSourceHistoryStore,
  ) {}

  async beginSelfModRun(args: {
    runId: string;
    taskDescription: string;
    packageId?: string;
    releaseNumber?: number;
    applyMode?: SelfModApplyMode;
  }): Promise<void> {
    const taskDescription = args.taskDescription.trim() || "Self mod update";
    const packageId = trimOrUndefined(args.packageId);
    const releaseNumber = normalizeReleaseNumber(args.releaseNumber);
    const baselineDirtyFiles = new Set(await listGitDirtyFiles(this.repoRoot));
    this.activeRuns.set(args.runId, {
      baselineDirtyFiles,
      taskDescription,
      ...(packageId ? { packageId } : {}),
      ...(releaseNumber == null ? {} : { releaseNumber }),
      applyMode: args.applyMode ?? "author",
    });
  }

  cancelSelfModRun(runId: string): void {
    this.activeRuns.delete(runId);
  }

  /**
   * Resolves once all queued post-commit background work (source
   * history, feature snapshot) has settled. Call before shutdown and
   * from tests that assert on deferred side effects.
   */
  async waitForBackgroundTasks(): Promise<void> {
    let tail: Promise<void>;
    do {
      tail = this.backgroundQueue;
      await tail;
      // New work may have been queued while awaiting; loop until stable.
    } while (tail !== this.backgroundQueue);
  }

  private enqueueBackgroundTask(task: () => Promise<void>): void {
    this.backgroundQueue = this.backgroundQueue.then(task).catch((error) => {
      console.warn(
        "[self-mod] background post-commit task failed (continuing):",
        (error as Error).message,
      );
    });
  }

  async finalizeSelfModRun(args: {
    runId: string;
    succeeded: boolean;
    /** Conversation that produced these changes; recorded as a commit trailer. */
    conversationId?: string;
    /**
     * Engine thread key of the agent that produced the changes
     * (orchestrator: equals `conversationId`; resumable subagents: the
     * persisted thread/agent id). Recorded as the `Stella-Thread`
     * commit trailer so a future revert can route the "user undid"
     * notice back to the same thread when the orchestrator resumes it.
     */
    threadKey?: string;
    /**
     * Concurrent-run attribution guard: returns true when another
     * still-active self-mod run owns `repoRelativePath`. Files owned by
     * a concurrent run are excluded from THIS run's commit (they stay
     * dirty and commit with their own run), so commit trailers never
     * attribute another agent's work to this conversation.
     */
    isPathOwnedByAnotherActiveRun?: (repoRelativePath: string) => boolean;
    commitMessageProvider?: CommitMessageProvider;
    /**
     * Optional rolling-window namer. Regenerated in the background after
     * a successful author-mode commit; the returned items replace the
     * snapshot the side panel reads.
     */
    featureNamerProvider?: FeatureNamerProvider;
  }): Promise<FinalizedSelfModCommit | null> {
    const activeRun = this.activeRuns.get(args.runId);
    this.activeRuns.delete(args.runId);
    if (!activeRun || !args.succeeded) {
      return null;
    }

    const currentDirtyFiles = normalizeFileList(
      await listGitDirtyFiles(this.repoRoot),
    );
    if (currentDirtyFiles.length === 0) {
      return null;
    }

    const baselineDirty = activeRun.baselineDirtyFiles;
    const blockedFiles: string[] = [];
    const safeFiles: string[] = [];
    for (const file of currentDirtyFiles) {
      if (baselineDirty.has(file)) {
        blockedFiles.push(file);
      } else if (args.isPathOwnedByAnotherActiveRun?.(file)) {
        blockedFiles.push(file);
      } else {
        safeFiles.push(file);
      }
    }
    if (safeFiles.length === 0) {
      return null;
    }

    const conversationTrailer = sanitizeTrailerOrWarn(
      args.conversationId,
      "Stella-Conversation",
    );
    const threadTrailer = sanitizeTrailerOrWarn(
      args.threadKey,
      "Stella-Thread",
    );
    const subject =
      activeRun.applyMode === "author"
        ? await this.deriveCommitSubject({
            activeRun,
            safeFiles,
            conversationTrailer,
            commitMessageProvider: args.commitMessageProvider,
          })
        : this.deriveInstallCommitSubject(activeRun);

    const trailers: Record<string, string> = {};
    if (conversationTrailer) {
      trailers["Stella-Conversation"] = conversationTrailer;
    }
    if (threadTrailer) {
      trailers["Stella-Thread"] = threadTrailer;
    }
    if (activeRun.applyMode !== "author") {
      if (activeRun.packageId) {
        trailers["Stella-Package-Id"] = activeRun.packageId;
      }
      if (activeRun.releaseNumber != null) {
        trailers["Stella-Release-Number"] = String(activeRun.releaseNumber);
      }
      if (activeRun.taskDescription) {
        trailers["Stella-Task"] = activeRun.taskDescription;
      }
    }

    const commitHash = await commitGitMessage({
      repoRoot: this.repoRoot,
      subject,
      trailers,
      paths: safeFiles,
    });
    if (!commitHash) {
      return null;
    }

    if (activeRun.applyMode === "author") {
      // Author-mode commits run source-history recording and the namer
      // LLM off the critical path: the worker's apply/morph (or pending
      // "Update" card) only needs the commit hash, and waiting on a
      // second LLM round-trip here visibly delays the change landing.
      const namer = args.featureNamerProvider;
      this.enqueueBackgroundTask(async () => {
        await this.recordSourceRevisionForCommit({
          activeRun,
          commitHash,
          subject,
          conversationTrailer,
        }).catch((error) => {
          console.warn(
            "[self-mod] source history recording failed (continuing):",
            (error as Error).message,
          );
        });
        if (namer) {
          await this.regenerateFeatureSnapshot(namer).catch((error) => {
            console.warn(
              "[self-mod] feature snapshot regeneration failed (continuing):",
              (error as Error).message,
            );
          });
        }
      });
      return {
        commitHash,
        files: safeFiles,
        blockedFiles,
      };
    }

    // Store install/update/uninstall and desktop-update commits need the
    // source revision id synchronously — it lands in the install ledger.
    const sourceRevisionId = await this.recordSourceRevisionForCommit({
      activeRun,
      commitHash,
      subject,
      conversationTrailer,
    }).catch((error) => {
      console.warn(
        "[self-mod] source history recording failed (continuing):",
        (error as Error).message,
      );
      return null;
    });

    return {
      commitHash,
      files: safeFiles,
      blockedFiles,
      ...(sourceRevisionId ? { sourceRevisionId } : {}),
    };
  }

  private async recordSourceRevisionForCommit(args: {
    activeRun: ActiveSelfModRun;
    commitHash: string;
    subject: string;
    conversationTrailer: string | undefined;
  }): Promise<string | null> {
    if (!this.sourceHistory) return null;
    const parentCommitHash = await getGitCommitParent(
      this.repoRoot,
      args.commitHash,
    );
    const parentRevision = parentCommitHash
      ? this.sourceHistory.findRevisionByCommit(parentCommitHash)
      : null;
    const featureId = args.activeRun.packageId
      ? `store:${args.activeRun.packageId}`
      : args.conversationTrailer
        ? `self-mod:${args.conversationTrailer}`
        : `self-mod:${args.commitHash}`;
    const origin: StellaSourceRevisionOrigin =
      args.activeRun.applyMode === "install"
        ? "store-install"
        : args.activeRun.applyMode === "update"
          ? "store-update"
          : args.activeRun.applyMode === "uninstall"
            ? "store-uninstall"
            : args.activeRun.applyMode === "desktop-update"
              ? "desktop-update"
              : "self-mod";
    const { changeSet } = await buildStellaSourceChangeSetForGitCommit({
      repoRoot: this.repoRoot,
      commitHash: args.commitHash,
      parentRevisionId: parentRevision?.revisionId,
      featureId,
      description: args.subject,
    });
    const record = this.sourceHistory.recordRevision({
      changeSet,
      origin,
      commitHash: args.commitHash,
      ...(args.activeRun.packageId
        ? { packageId: args.activeRun.packageId }
        : {}),
      ...(args.activeRun.releaseNumber != null
        ? { releaseNumber: args.activeRun.releaseNumber }
        : {}),
      featureId,
      description: args.subject,
    });
    return record.revisionId;
  }

  private async deriveCommitSubject(args: {
    activeRun: ActiveSelfModRun;
    safeFiles: string[];
    conversationTrailer: string | undefined;
    commitMessageProvider: CommitMessageProvider | undefined;
  }): Promise<string> {
    const fallback =
      trimOrUndefined(args.activeRun.taskDescription) ?? "Self mod update";
    if (!args.commitMessageProvider) {
      return fallback;
    }
    let diffPreview = "";
    try {
      diffPreview = await getStagedDiffPreview(this.repoRoot, {
        paths: args.safeFiles,
      });
    } catch {
      diffPreview = "";
    }
    try {
      const result = await args.commitMessageProvider({
        taskDescription: args.activeRun.taskDescription,
        files: args.safeFiles,
        diffPreview,
        ...(args.conversationTrailer
          ? { conversationId: args.conversationTrailer }
          : {}),
      });
      const trimmed = result?.trim();
      return trimmed && trimmed.length > 0 ? trimmed : fallback;
    } catch {
      return fallback;
    }
  }

  private deriveInstallCommitSubject(activeRun: ActiveSelfModRun): string {
    const subjectPrefix =
      activeRun.applyMode === "uninstall"
        ? "Store uninstall"
        : activeRun.applyMode === "update"
          ? "Store update"
          : activeRun.applyMode === "desktop-update"
            ? "Desktop update"
            : "Store install";
    return activeRun.packageId
      ? `${subjectPrefix}: ${activeRun.packageId}`
      : subjectPrefix;
  }

  private async regenerateFeatureSnapshot(
    provider: FeatureNamerProvider,
  ): Promise<void> {
    const firstCommit = await this.getFirstRepoCommit();
    const recent = await listRecentGitCommits(
      this.repoRoot,
      ROLLING_WINDOW_SIZE + 1,
    );
    const filtered = recent
      .filter((commit) => commit.commitHash !== firstCommit)
      .slice(0, ROLLING_WINDOW_SIZE);
    if (filtered.length === 0) {
      return;
    }
    const previousItems = this.store.readFeatureSnapshot()?.items ?? [];
    const items = await provider({
      commits: filtered.map((commit) => ({
        commitHash: commit.commitHash,
        shortHash: commit.shortHash,
        subject: commit.subject,
        body: commit.body,
        timestampMs: commit.timestampMs,
        files: commit.files,
      })),
      previousItems,
    });
    if (!items) return;
    this.store.writeFeatureSnapshot({
      items,
      generatedAt: Date.now(),
    });
  }

  private async getFirstRepoCommit(): Promise<string | null> {
    if (this.firstRepoCommit !== undefined) {
      return this.firstRepoCommit;
    }
    try {
      const { env, gitLocation } = setupEnvironment({});
      const result = await execFileAsync(
        gitLocation,
        ["rev-list", "--max-parents=0", "HEAD"],
        {
          cwd: this.repoRoot,
          env,
          encoding: "utf8",
          windowsHide: true,
        },
      );
      const stdout = result.stdout;
      const lines = stdout
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean);
      this.firstRepoCommit = lines[lines.length - 1] ?? null;
      return this.firstRepoCommit;
    } catch {
      this.firstRepoCommit = null;
      return null;
    }
  }

  readFeatureSnapshot(): SelfModFeatureSnapshot | null {
    return this.store.readFeatureSnapshot();
  }

  recordInstall(args: {
    packageId: string;
    releaseNumber: number;
    installCommitHash: string | null;
    sourceRevisionId?: string | null;
    sourceRevisionIds?: string[];
  }): StoreInstallRecord {
    return this.store.recordInstall(args);
  }

  getInstall(packageId: string): StoreInstallRecord | null {
    return this.store.getInstall(packageId);
  }

  listInstalls(): StoreInstallRecord[] {
    return this.store.listInstalls();
  }

  async uninstall(packageId: string): Promise<{
    revertedCommits: string[];
    fallbackRequired: boolean;
    reason?: string;
  }> {
    const install = this.store.getInstall(packageId);
    if (!install) {
      return { revertedCommits: [], fallbackRequired: false };
    }
    let revertedCommits: string[] = [];
    const hashes =
      install.installCommitHashes.length > 0
        ? install.installCommitHashes
        : install.installCommitHash
          ? [install.installCommitHash]
          : [];
    if (hashes.length > 0) {
      const dirtyFiles = await listGitDirtyFiles(this.repoRoot);
      if (dirtyFiles.length > 0) {
        return {
          revertedCommits: [],
          fallbackRequired: true,
          reason: "working tree is not clean",
        };
      }
      const expectedHeadStack = [...hashes].reverse();
      const actualHeadStack = await getGitHeadCommitSequence(
        this.repoRoot,
        expectedHeadStack.length,
      );
      const canDirectRevert =
        actualHeadStack.length === expectedHeadStack.length &&
        expectedHeadStack.every(
          (hash, index) => actualHeadStack[index] === hash,
        );
      if (!canDirectRevert) {
        return {
          revertedCommits: [],
          fallbackRequired: true,
          reason: "install commits are not the latest commits",
        };
      }
      try {
        // The tree was just verified clean, so a mid-stack revert
        // failure can safely reset back to the pre-revert HEAD instead
        // of leaving a half-uninstalled history.
        revertedCommits = await revertGitCommits({
          repoRoot: this.repoRoot,
          commitHashes: expectedHeadStack,
          resetToPreRevertHeadOnFailure: true,
        });
      } catch (error) {
        throw new Error(
          `Failed to revert install commits for ${packageId}: ${(error as Error).message}`,
        );
      }
    }
    this.store.deleteInstall(packageId);
    return { revertedCommits, fallbackRequired: false };
  }

  forgetInstall(packageId: string): void {
    this.store.deleteInstall(packageId);
  }
}
