import type {
  SelfModFeatureSnapshot,
  StoreInstallRecord,
} from "../../contracts/index.js";
import { StoreModStore } from "../storage/store-mod-store.js";
import {
  commitGitMessage,
  getGitHeadCommitSequence,
  getStagedDiffPreview,
  listGitDirtyFiles,
  listRecentGitCommits,
  revertGitCommits,
} from "./git.js";

export type CommitMessageProviderArgs = {
  /** What the agent was asked to do (subagent task description). */
  taskDescription: string;
  /** Files about to be committed (relative repo paths). */
  files: string[];
  /** Truncated unified diff of staged changes (may be empty). */
  diffPreview: string;
  /** Conversation that produced these changes; used as a context hint. */
  conversationId?: string;
};

/**
 * Provider for the agent-authored commit subject. Returning `null` (or
 * an empty string) falls back to the run's task description.
 */
export type CommitMessageProvider = (
  args: CommitMessageProviderArgs,
) => Promise<string | null>;

/**
 * Provider for the rolling-window feature namer. Receives the most
 * recent self-mod commits (excluding the repo's first-ever commit) and
 * returns a normie-friendly grouped list of names. Returning `null`
 * leaves the previous snapshot in place.
 */
export type FeatureNamerProvider = (args: {
  commits: Array<{
    commitHash: string;
    shortHash: string;
    subject: string;
    body: string;
    timestampMs: number;
    files: string[];
  }>;
}) => Promise<SelfModFeatureSnapshot["items"] | null>;

type ActiveSelfModRun = {
  baselineDirtyFiles: Set<string>;
  taskDescription: string;
  packageId?: string;
  releaseNumber?: number;
  applyMode: "author" | "install" | "update" | "uninstall";
};

export type FinalizedSelfModCommit = {
  commitHash: string;
  files: string[];
  blockedFiles: string[];
};

const ROLLING_WINDOW_SIZE = 10;

const normalizeFileList = (files: string[]): string[] =>
  Array.from(
    new Set(
      files.map((file) => file.trim().replace(/\\/g, "/")).filter(Boolean),
    ),
  ).sort();

const sanitizeConversationTrailer = (
  value: string | undefined,
): string | undefined => {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;
  if (!/^[A-Za-z0-9._:\-]{1,200}$/.test(trimmed)) {
    return undefined;
  }
  return trimmed;
};

const trimOrUndefined = (value: string | undefined): string | undefined => {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
};

const normalizeReleaseNumber = (
  value: number | undefined,
): number | undefined =>
  typeof value === "number" && Number.isFinite(value)
    ? Math.max(1, Math.floor(value))
    : undefined;

/**
 * Owns the self-mod commit lifecycle and the install ledger. Per-commit
 * grouping/feature-roster stuff is gone — the side panel reads a
 * rolling-window snapshot regenerated by the cheap-LLM namer after each
 * commit.
 */
export class StoreModService {
  private readonly activeRuns = new Map<string, ActiveSelfModRun>();
  private firstRepoCommit: string | null | undefined = undefined;

  constructor(
    private readonly repoRoot: string,
    private readonly store: StoreModStore,
  ) {}

  async beginSelfModRun(args: {
    runId: string;
    taskDescription: string;
    packageId?: string;
    releaseNumber?: number;
    applyMode?: "author" | "install" | "update" | "uninstall";
  }): Promise<void> {
    const taskDescription = args.taskDescription.trim() || "Self mod update";
    const packageId = trimOrUndefined(args.packageId);
    const releaseNumber = normalizeReleaseNumber(args.releaseNumber);
    const baselineDirtyFiles = new Set(await listGitDirtyFiles(this.repoRoot));
    this.activeRuns.set(args.runId, {
      baselineDirtyFiles,
      taskDescription,
      ...(packageId ? { packageId } : {}),
      ...(releaseNumber == null ? {} : { releaseNumber }),
      applyMode: args.applyMode ?? "author",
    });
  }

  cancelSelfModRun(runId: string): void {
    this.activeRuns.delete(runId);
  }

  async finalizeSelfModRun(args: {
    runId: string;
    succeeded: boolean;
    /** Conversation that produced these changes; recorded as a commit trailer. */
    conversationId?: string;
    /**
     * Engine thread key of the agent that produced the changes
     * (orchestrator: equals `conversationId`; resumable subagents: the
     * persisted thread/agent id). Recorded as the `Stella-Thread`
     * commit trailer so a future revert can route the "user undid"
     * notice back to the same thread when the orchestrator resumes it.
     */
    threadKey?: string;
    commitMessageProvider?: CommitMessageProvider;
    /**
     * Optional rolling-window namer. Called after a successful commit
     * with the most recent self-mod commits; the returned items replace
     * the snapshot the side panel reads.
     */
    featureNamerProvider?: FeatureNamerProvider;
  }): Promise<FinalizedSelfModCommit | null> {
    const activeRun = this.activeRuns.get(args.runId);
    this.activeRuns.delete(args.runId);
    if (!activeRun || !args.succeeded) {
      return null;
    }

    const currentDirtyFiles = normalizeFileList(
      await listGitDirtyFiles(this.repoRoot),
    );
    if (currentDirtyFiles.length === 0) {
      return null;
    }

    const baselineDirty = activeRun.baselineDirtyFiles;
    const blockedFiles = currentDirtyFiles.filter((file) =>
      baselineDirty.has(file),
    );
    const safeFiles = currentDirtyFiles.filter(
      (file) => !baselineDirty.has(file),
    );
    if (safeFiles.length === 0) {
      return null;
    }

    const conversationTrailer = sanitizeConversationTrailer(
      args.conversationId,
    );
    // Reuses `sanitizeConversationTrailer`'s allowlist. The two
    // upstream callers pass either (a) `conversationId` (orchestrator
    // self-mod commits, `orchestrator-launch.ts`) or (b) `agentId`
    // (resumable subagent commits, `agent-orchestration.ts`). Both
    // fit the `[A-Za-z0-9._:\-]{1,200}` allowlist today. If a new
    // caller wires the synthesized `buildRuntimeThreadKey` form
    // (`${conversationId}::subagent::${agentType}::run:${runId}`) or
    // anything else outside that allowlist, update the sanitizer in
    // lockstep or the trailer silently drops and revert-routing falls
    // back to orchestrator-only.
    const threadTrailer = sanitizeConversationTrailer(args.threadKey);
    const subject =
      activeRun.applyMode === "author"
        ? await this.deriveCommitSubject({
            activeRun,
            safeFiles,
            conversationTrailer,
            commitMessageProvider: args.commitMessageProvider,
          })
        : this.deriveInstallCommitSubject(activeRun);

    const trailers: Record<string, string> = {};
    if (conversationTrailer) {
      trailers["Stella-Conversation"] = conversationTrailer;
    }
    if (threadTrailer) {
      trailers["Stella-Thread"] = threadTrailer;
    }
    if (activeRun.applyMode !== "author") {
      if (activeRun.packageId) {
        trailers["Stella-Package-Id"] = activeRun.packageId;
      }
      if (activeRun.releaseNumber != null) {
        trailers["Stella-Release-Number"] = String(activeRun.releaseNumber);
      }
      if (activeRun.taskDescription) {
        trailers["Stella-Task"] = activeRun.taskDescription;
      }
    }

    const commitHash = await commitGitMessage({
      repoRoot: this.repoRoot,
      subject,
      trailers,
      paths: safeFiles,
    });
    if (!commitHash) {
      return null;
    }

    if (activeRun.applyMode === "author" && args.featureNamerProvider) {
      await this.regenerateFeatureSnapshot(args.featureNamerProvider).catch(
        (error) => {
          console.warn(
            "[self-mod] feature snapshot regeneration failed (continuing):",
            (error as Error).message,
          );
        },
      );
    }

    return {
      commitHash,
      files: safeFiles,
      blockedFiles,
    };
  }

  private async deriveCommitSubject(args: {
    activeRun: ActiveSelfModRun;
    safeFiles: string[];
    conversationTrailer: string | undefined;
    commitMessageProvider: CommitMessageProvider | undefined;
  }): Promise<string> {
    const fallback =
      trimOrUndefined(args.activeRun.taskDescription) ?? "Self mod update";
    if (!args.commitMessageProvider) {
      return fallback;
    }
    let diffPreview = "";
    try {
      diffPreview = await getStagedDiffPreview(this.repoRoot, {
        paths: args.safeFiles,
      });
    } catch {
      diffPreview = "";
    }
    try {
      const result = await args.commitMessageProvider({
        taskDescription: args.activeRun.taskDescription,
        files: args.safeFiles,
        diffPreview,
        ...(args.conversationTrailer
          ? { conversationId: args.conversationTrailer }
          : {}),
      });
      const trimmed = result?.trim();
      return trimmed && trimmed.length > 0 ? trimmed : fallback;
    } catch {
      return fallback;
    }
  }

  private deriveInstallCommitSubject(activeRun: ActiveSelfModRun): string {
    const subjectPrefix =
      activeRun.applyMode === "uninstall"
        ? "Store uninstall"
        : activeRun.applyMode === "update"
          ? "Store update"
          : "Store install";
    return activeRun.packageId
      ? `${subjectPrefix}: ${activeRun.packageId}`
      : subjectPrefix;
  }

  private async regenerateFeatureSnapshot(
    provider: FeatureNamerProvider,
  ): Promise<void> {
    const firstCommit = await this.getFirstRepoCommit();
    const recent = await listRecentGitCommits(
      this.repoRoot,
      ROLLING_WINDOW_SIZE + 1,
    );
    const filtered = recent
      .filter((commit) => commit.commitHash !== firstCommit)
      .slice(0, ROLLING_WINDOW_SIZE);
    if (filtered.length === 0) {
      return;
    }
    const items = await provider({
      commits: filtered.map((commit) => ({
        commitHash: commit.commitHash,
        shortHash: commit.shortHash,
        subject: commit.subject,
        body: commit.body,
        timestampMs: commit.timestampMs,
        files: commit.files,
      })),
    });
    if (!items) return;
    this.store.writeFeatureSnapshot({
      items,
      generatedAt: Date.now(),
    });
  }

  private async getFirstRepoCommit(): Promise<string | null> {
    if (this.firstRepoCommit !== undefined) {
      return this.firstRepoCommit;
    }
    try {
      const { exec } = await import("dugite");
      const result = await exec(
        ["rev-list", "--max-parents=0", "HEAD"],
        this.repoRoot,
        { encoding: "utf8" },
      );
      if (result.exitCode !== 0) {
        this.firstRepoCommit = null;
        return null;
      }
      const stdout =
        typeof result.stdout === "string"
          ? result.stdout
          : Buffer.from(result.stdout).toString("utf8");
      const lines = stdout
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean);
      this.firstRepoCommit = lines[lines.length - 1] ?? null;
      return this.firstRepoCommit;
    } catch {
      this.firstRepoCommit = null;
      return null;
    }
  }

  readFeatureSnapshot(): SelfModFeatureSnapshot | null {
    return this.store.readFeatureSnapshot();
  }

  recordInstall(args: {
    packageId: string;
    releaseNumber: number;
    installCommitHash: string | null;
  }): StoreInstallRecord {
    return this.store.recordInstall(args);
  }

  getInstall(packageId: string): StoreInstallRecord | null {
    return this.store.getInstall(packageId);
  }

  listInstalls(): StoreInstallRecord[] {
    return this.store.listInstalls();
  }

  async uninstall(packageId: string): Promise<{
    revertedCommits: string[];
    fallbackRequired: boolean;
    reason?: string;
  }> {
    const install = this.store.getInstall(packageId);
    if (!install) {
      return { revertedCommits: [], fallbackRequired: false };
    }
    let revertedCommits: string[] = [];
    const hashes =
      install.installCommitHashes.length > 0
        ? install.installCommitHashes
        : install.installCommitHash
          ? [install.installCommitHash]
          : [];
    if (hashes.length > 0) {
      const dirtyFiles = await listGitDirtyFiles(this.repoRoot);
      if (dirtyFiles.length > 0) {
        return {
          revertedCommits: [],
          fallbackRequired: true,
          reason: "working tree is not clean",
        };
      }
      const expectedHeadStack = [...hashes].reverse();
      const actualHeadStack = await getGitHeadCommitSequence(
        this.repoRoot,
        expectedHeadStack.length,
      );
      const canDirectRevert =
        actualHeadStack.length === expectedHeadStack.length &&
        expectedHeadStack.every((hash, index) => actualHeadStack[index] === hash);
      if (!canDirectRevert) {
        return {
          revertedCommits: [],
          fallbackRequired: true,
          reason: "install commits are not the latest commits",
        };
      }
      try {
        revertedCommits = await revertGitCommits({
          repoRoot: this.repoRoot,
          commitHashes: expectedHeadStack,
        });
      } catch (error) {
        throw new Error(
          `Failed to revert install commits for ${packageId}: ${(error as Error).message}`,
        );
      }
    }
    this.store.deleteInstall(packageId);
    return { revertedCommits, fallbackRequired: false };
  }

  forgetInstall(packageId: string): void {
    this.store.deleteInstall(packageId);
  }
}
