const EMBEDDED_DISPOSABLE_DOMAINS = new Set(
  `
0-mail.com
0815.ru
10mail.org
10minemail.com
10minutemail.com
10minutemail.net
10minutemail.org
10minutemail.co.za
20minutemail.com
2prong.com
33mail.com
3d-painting.com
4warding.com
5ymail.com
6paq.com
7tags.com
9ox.net
anonbox.net
anonymbox.com
antichef.com
antichef.net
antispam.de
armyspy.com
bccto.me
beefmilk.com
bigstring.com
binkmail.com
bio-muesli.net
bladesmail.net
bofthew.com
bootybay.de
boun.cr
bouncr.com
boximail.com
bugmenot.com
bund.us
byom.de
cachedot.net
casualdx.com
cek.pm
centermail.com
centermail.net
chammy.info
chogmail.com
choicemail1.com
clixser.com
cmail.net
cmail.org
cock.li
cool.fr.nf
correo.blogos.net
cosmorph.com
courriel.fr.nf
cubiclink.com
curryworld.de
dacoolest.com
dandikmail.com
dayrep.com
deadaddress.com
deadspam.com
despam.it
devnullmail.com
digitalsanctuary.com
dingbone.com
discard.email
discardmail.com
discardmail.de
disposable.com
disposableaddress.com
disposableemailaddresses.com
disposableinbox.com
dispose.it
disposeamail.com
disposemail.com
dispostable.com
dm.w3internet.co.uk
dodgeit.com
dodgit.com
dodgit.org
donemail.ru
dontreg.com
dontsendmespam.de
drdrb.com
dump-email.info
dumpandjunk.com
dumpmail.de
dumpyemail.com
e4ward.com
email60.com
emailias.com
emailigo.de
emailinfive.com
emailmiser.com
emailondeck.com
emailsensei.com
emailtemporanea.com
emailtemporanea.net
emailtemporario.com.br
emailthe.net
emailwarden.com
emailx.at.hm
emailxfer.com
emeil.in
emeil.ir
emz.net
enterto.com
ephemail.net
etranquil.com
etranquil.net
etranquil.org
evopo.com
explodemail.com
express.net.ua
eyepaste.com
fakeinbox.com
fakeinformation.com
fansworldwide.de
fantasymail.de
filzmail.com
fizmail.com
flyspam.com
frapmail.com
garliclife.com
get1mail.com
get2mail.fr
getairmail.com
getmails.eu
getnada.com
getonemail.com
getonemail.net
girlsundertheinfluence.com
gishpuppy.com
gowikibooks.com
gowikicampus.com
gowikicars.com
gowikifilms.com
gowikigames.com
gowikimusic.com
gowikinetwork.com
gowikitravel.com
gowikitv.com
grandmamail.com
great-host.in
greensloth.com
grr.la
guerrillamail.biz
guerrillamail.com
guerrillamail.de
guerrillamail.info
guerrillamail.net
guerrillamail.org
guerrillamailblock.com
gustr.com
harakirimail.com
hat-geld.de
hatespam.org
hidemail.de
hidzz.com
hmamail.com
hopemail.biz
hotpop.com
hulapla.de
ieatspam.eu
ieatspam.info
imails.info
inbax.tk
inboxalias.com
inboxclean.com
inboxclean.org
inboxproxy.com
incognitomail.com
incognitomail.net
incognitomail.org
insorg-mail.info
instant-mail.de
ip6.li
irish2me.com
iwi.net
jetable.com
jetable.fr.nf
jetable.net
jetable.org
jmail.ro
jnxjn.com
jourrapide.com
jsrsolutions.com
kasmail.com
kaspop.com
killmail.com
killmail.net
kir.ch.tc
klassmaster.com
klzlk.com
kulturbetrieb.info
kurzepost.de
lawlita.com
letthemeatspam.com
litedrop.com
lol.ovpn.to
lookugly.com
lopl.co.cc
lortemail.dk
lr78.com
m4ilweb.info
maboard.com
mail-temporaire.fr
mail.by
mail.mezimages.net
mail333.com
mail4trash.com
mailbidon.com
mailblocks.com
mailcatch.com
mailcatcher.info
maildrop.cc
maildrop.cf
maildrop.ga
maildrop.gq
maildrop.ml
maildu.de
maileater.com
mailexpire.com
mailfa.tk
mailforspam.com
mailfreeonline.com
mailguard.me
mailimate.com
mailin8r.com
mailinater.com
mailinator.com
mailinator.net
mailinator.org
mailinator2.com
mailincubator.com
mailismagic.com
mailme.lv
mailme24.com
mailmetrash.com
mailmoat.com
mailnator.com
mailnesia.com
mailnull.com
mailorg.org
mailpick.biz
mailproxsy.com
mailsac.com
mailscrap.com
mailshell.com
mailsiphon.com
mailslite.com
mailtemp.info
mailtome.de
mailtothis.com
mailzilla.com
mbx.cc
meltmail.com
messagebeamer.de
mezimages.net
mintemail.com
misterpinball.de
moncourrier.fr.nf
monemail.fr.nf
monmail.fr.nf
mt2009.com
mx0.wwwnew.eu
mycard.net.ua
mycleaninbox.net
mymail-in.net
mymailoasis.com
mynetstore.de
myphantomemail.com
myspaceinc.com
myspaceinc.net
myspaceinc.org
myspamless.com
mytrashmail.com
neomailbox.com
nepwk.com
nervmich.net
nervtmich.net
netmails.com
netmails.net
neverbox.com
no-spam.ws
nobulk.com
noclickemail.com
nogmailspam.info
nomail.xl.cx
nomail2me.com
nomorespamemails.com
nospam.ze.tc
nospam4.us
nospamfor.us
nospammail.net
nospamthanks.info
notmailinator.com
nowmymail.com
objectmail.com
obobbo.com
oneoffemail.com
onewaymail.com
ordinaryamerican.net
owlpic.com
pjjkp.com
plexolan.de
pookmail.com
privacy.net
proxymail.eu
prtnx.com
punkass.com
putthisinyourspamdatabase.com
quickinbox.com
rcpt.at
reallymymail.com
recode.me
recursor.net
regbypass.com
rejectmail.com
rhyta.com
rklips.com
rmqkr.net
royal.net
rppkn.com
rtrtr.com
s0ny.net
safe-mail.net
safetymail.info
safetypost.de
saynotospams.com
schafmail.de
selfdestructingmail.com
sendspamhere.com
shiftmail.com
shitmail.me
sharklasers.com
skeefmail.com
slaskpost.se
slopsbox.com
smashmail.de
smellfear.com
snakemail.com
sneakemail.com
sofort-mail.de
sofortmail.de
spam.la
spam.su
spam4.me
spamavert.com
spambob.com
spambob.net
spambob.org
spambog.com
spambog.de
spambog.ru
spambox.info
spambox.us
spamcannon.com
spamcannon.net
spamcon.org
spamcorptastic.com
spamcowboy.com
spamcowboy.net
spamcowboy.org
spamday.com
spamex.com
spamfree24.com
spamfree24.de
spamfree24.eu
spamfree24.info
spamfree24.net
spamfree24.org
spamgourmet.com
spamgourmet.net
spamgourmet.org
spamherelots.com
spamhereplease.com
spamhole.com
spamify.com
spaminator.de
spamkill.info
spaml.com
spaml.de
spammotel.com
spamobox.com
spamoff.de
spamslicer.com
spamspot.com
spamstack.net
spamthis.co.uk
spamthisplease.com
spamtrail.com
speed.1s.fr
spoofmail.de
squizzy.de
ssoia.com
supergreatmail.com
supermailer.jp
suremail.info
teewars.org
teleworm.com
temp-mail.org
temp-mail.ru
tempalias.com
tempe-mail.com
tempemail.biz
tempemail.com
tempemail.net
tempinbox.co.uk
tempinbox.com
tempmail.eu
tempmail.it
tempmail2.com
tempmaildemo.com
tempmailer.com
tempmailer.de
tempomail.fr
temporarily.de
temporaryemail.net
temporaryforwarding.com
temporaryinbox.com
temporarymailaddress.com
tempthe.net
thankyou2010.com
thisisnotmyrealemail.com
throwawayemailaddress.com
tilien.com
tmailinator.com
tradermail.info
trash-mail.at
trash-mail.com
trash-mail.de
trash2009.com
trashdevil.com
trashemail.de
trashmail.at
trashmail.com
trashmail.de
trashmail.me
trashmail.net
trashmail.org
trashymail.com
trashymail.net
trbvm.com
turual.com
twinmail.de
tyldd.com
uggsrock.com
wegwerfadresse.de
wegwerfemail.com
wegwerfemail.de
wegwerfmail.de
wegwerfmail.net
wegwerfmail.org
wh4f.org
whatiaas.com
whatpaas.com
whopy.com
willhackforfood.biz
willselfdestruct.com
winemaven.info
wronghead.com
wuzup.net
xagloo.com
xemaps.com
xents.com
xoxy.net
yapped.net
yeah.net
yep.it
yogamaven.com
yopmail.com
yopmail.fr
yopmail.net
yuurok.com
zehnminutenmail.de
zippymail.info
zoemail.org
`.trim()
    .split(/\s+/u)
    .map((domain) => domain.toLowerCase()),
);

const normalizeDomain = (value: string): string =>
  value.trim().toLowerCase().replace(/^@/u, "").replace(/\.+$/u, "");

const emailDomain = (email: string): string | null => {
  const normalized = email.trim().toLowerCase();
  const separator = normalized.lastIndexOf("@");
  if (separator <= 0 || separator === normalized.length - 1) return null;
  const domain = normalizeDomain(normalized.slice(separator + 1));
  return domain || null;
};

const configuredBlockedDomains = (): string[] =>
  (process.env.STELLA_EMAIL_DOMAIN_BLOCKLIST ?? "")
    .split(",")
    .map(normalizeDomain)
    .filter(Boolean);

const matchesDomainOrSubdomain = (
  domain: string,
  blockedDomain: string,
): boolean => domain === blockedDomain || domain.endsWith(`.${blockedDomain}`);

export const isDisposableEmail = (email: string): boolean => {
  const domain = emailDomain(email);
  if (!domain) return false;
  for (const blockedDomain of EMBEDDED_DISPOSABLE_DOMAINS) {
    if (matchesDomainOrSubdomain(domain, blockedDomain)) return true;
  }
  return configuredBlockedDomains().some((blockedDomain) =>
    matchesDomainOrSubdomain(domain, blockedDomain),
  );
};

export const normalizeEmailForSybil = (email: string): string => {
  const normalized = email.trim().toLowerCase();
  const separator = normalized.lastIndexOf("@");
  if (separator <= 0 || separator === normalized.length - 1) return normalized;

  let local = normalized.slice(0, separator);
  let domain = normalizeDomain(normalized.slice(separator + 1));
  if (domain === "gmail.com" || domain === "googlemail.com") {
    local = (local.split("+", 1)[0] ?? "").replaceAll(".", "");
    domain = "gmail.com";
  }
  return `${local}@${domain}`;
};

export const embeddedDisposableDomainCount = (): number =>
  EMBEDDED_DISPOSABLE_DOMAINS.size;
