export type ComposioManagedToolkit = {
  slug: string;
  name: string;
};

export const COMPOSIO_MANAGED_TOOLKITS = [
  { slug: "airtable", name: "Airtable" },
  { slug: "apaleo", name: "Apaleo" },
  { slug: "asana", name: "Asana" },
  { slug: "attio", name: "Attio" },
  { slug: "basecamp", name: "Basecamp" },
  { slug: "bitbucket", name: "Bitbucket" },
  { slug: "blackbaud", name: "Blackbaud" },
  { slug: "boldsign", name: "Boldsign" },
  { slug: "box", name: "Box" },
  { slug: "cal", name: "Cal" },
  { slug: "calendly", name: "Calendly" },
  { slug: "canva", name: "Canva" },
  { slug: "capsule_crm", name: "Capsule CRM" },
  { slug: "clickup", name: "ClickUp" },
  { slug: "confluence", name: "Confluence" },
  { slug: "contentful", name: "Contentful" },
  { slug: "convex", name: "Convex" },
  { slug: "crowdin", name: "Crowdin" },
  { slug: "dart", name: "Dart" },
  { slug: "dialpad", name: "Dialpad" },
  { slug: "digital_ocean", name: "DigitalOcean" },
  { slug: "discord", name: "Discord" },
  { slug: "discordbot", name: "Discord Bot" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "dub", name: "Dub" },
  { slug: "dynamics365", name: "Dynamics 365" },
  { slug: "eventbrite", name: "Eventbrite" },
  { slug: "excel", name: "Excel" },
  { slug: "exist", name: "Exist" },
  { slug: "facebook", name: "Facebook" },
  { slug: "fathom", name: "Fathom" },
  { slug: "figma", name: "Figma" },
  { slug: "freeagent", name: "Freeagent" },
  { slug: "freshbooks", name: "FreshBooks" },
  { slug: "github", name: "GitHub" },
  { slug: "gitlab", name: "GitLab" },
  { slug: "gmail", name: "Gmail" },
  { slug: "googleads", name: "Google Ads" },
  { slug: "google_analytics", name: "Google Analytics" },
  { slug: "googlebigquery", name: "Google BigQuery" },
  { slug: "googlecalendar", name: "Google Calendar" },
  { slug: "google_classroom", name: "Google Classroom" },
  { slug: "googledocs", name: "Google Docs" },
  { slug: "googledrive", name: "Google Drive" },
  { slug: "google_maps", name: "Google Maps" },
  { slug: "googlemeet", name: "Google Meet" },
  { slug: "googlephotos", name: "Google Photos" },
  { slug: "google_search_console", name: "Google Search Console" },
  { slug: "googlesheets", name: "Google Sheets" },
  { slug: "googleslides", name: "Google Slides" },
  { slug: "googlesuper", name: "Google Super" },
  { slug: "googletasks", name: "Google Tasks" },
  { slug: "gorgias", name: "Gorgias" },
  { slug: "gumroad", name: "Gumroad" },
  { slug: "harvest", name: "Harvest" },
  { slug: "hubspot", name: "HubSpot" },
  { slug: "hugging_face", name: "Hugging Face" },
  { slug: "instagram", name: "Instagram" },
  { slug: "intercom", name: "Intercom" },
  { slug: "jira", name: "Jira" },
  { slug: "kit", name: "Kit" },
  { slug: "linear", name: "Linear" },
  { slug: "linkedin", name: "LinkedIn" },
  { slug: "linkhut", name: "Linkhut" },
  { slug: "mailchimp", name: "Mailchimp" },
  { slug: "microsoft_teams", name: "Microsoft Teams" },
  { slug: "miro", name: "Miro" },
  { slug: "monday", name: "Monday" },
  { slug: "moneybird", name: "Moneybird" },
  { slug: "mural", name: "Mural" },
  { slug: "notion", name: "Notion" },
  { slug: "omnisend", name: "Omnisend" },
  { slug: "one_drive", name: "OneDrive" },
  { slug: "outlook", name: "Outlook" },
  { slug: "pagerduty", name: "PagerDuty" },
  { slug: "prisma", name: "Prisma" },
  { slug: "productboard", name: "Productboard" },
  { slug: "pushbullet", name: "Pushbullet" },
  { slug: "quickbooks", name: "QuickBooks" },
  { slug: "reddit", name: "Reddit" },
  { slug: "reddit_ads", name: "Reddit Ads" },
  { slug: "roam", name: "Roam" },
  { slug: "salesforce", name: "Salesforce" },
  { slug: "sentry", name: "Sentry" },
  { slug: "servicem8", name: "Servicem8" },
  { slug: "share_point", name: "SharePoint" },
  { slug: "shippo", name: "Shippo" },
  { slug: "slack", name: "Slack" },
  { slug: "slackbot", name: "Slackbot" },
  { slug: "splitwise", name: "Splitwise" },
  { slug: "square", name: "Square" },
  { slug: "stack_exchange", name: "Stack Exchange" },
  { slug: "strava", name: "Strava" },
  { slug: "stripe", name: "Stripe" },
  { slug: "supabase", name: "Supabase" },
  { slug: "ticketmaster", name: "Ticketmaster" },
  { slug: "ticktick", name: "Ticktick" },
  { slug: "timely", name: "Timely" },
  { slug: "todoist", name: "Todoist" },
  { slug: "toneden", name: "Toneden" },
  { slug: "trello", name: "Trello" },
  { slug: "typeform", name: "Typeform" },
  { slug: "wakatime", name: "WakaTime" },
  { slug: "webex", name: "Webex" },
  { slug: "whatsapp", name: "WhatsApp Business" },
  { slug: "wrike", name: "Wrike" },
  { slug: "yandex", name: "Yandex" },
  { slug: "ynab", name: "YNAB" },
  { slug: "youtube", name: "YouTube" },
  { slug: "zendesk", name: "Zendesk" },
  { slug: "zoho", name: "Zoho" },
  { slug: "zoho_bigin", name: "Zoho Bigin" },
  { slug: "zoho_books", name: "Zoho Books" },
  { slug: "zoho_desk", name: "Zoho Desk" },
  { slug: "zoho_inventory", name: "Zoho Inventory" },
  { slug: "zoho_invoice", name: "Zoho Invoice" },
  { slug: "zoho_mail", name: "Zoho Mail" },
  { slug: "zoom", name: "Zoom" },
] as const satisfies readonly ComposioManagedToolkit[];

export const getComposioManagedToolkit = (slug: string) =>
  COMPOSIO_MANAGED_TOOLKITS.find((entry) => entry.slug === slug);
