/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false` (hash: 6e754879a25803ee540aad42d0f1dcde)
interface __BaseEnv_Env {
	TELEMETRY_RATE_LIMITER: RateLimit;
	ENVIRONMENT: "production" | "development";
	STELLA_CONVEX_SITE_URL: "https://benevolent-minnow-586.convex.site" | "https://impartial-crab-34.convex.site";
	ENABLE_SERVER_BEARER: "1";
	TELEMETRY_PSEUDONYM_KEY: string;
	TELEMETRY_SERVER_SECRET: string;
	CONVEX_LOG_STREAM_SECRET: string;
	EVENTS_PIPELINE: import("cloudflare:pipelines").Pipeline<Cloudflare.StellaTelemetryProdStreamV1Record> | import("cloudflare:pipelines").Pipeline<Cloudflare.StellaTelemetryDevStreamV1Record>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	type StellaTelemetryProdStreamV1Record = { schema_version: number; event_id: string; occurred_at_ms: number; ingested_at_ms: number; project: string; environment: string; source: string; release?: string; installation_id_sha256?: string; owner_id_sha256: string; principal_kind: string; event_type: string; component?: string; phase?: string; duration_ms?: number; exit_code?: number; reason_code?: string; severity?: string; error_class?: string; error_code?: string; fingerprint?: string; recovered?: boolean; metric?: string; outcome?: string; provider?: string; model?: string; response_model?: string; agent_type?: string; success?: boolean; stop_reason?: string; input_tokens?: number; output_tokens?: number; cached_input_tokens?: number; cache_write_input_tokens?: number; reasoning_tokens?: number; total_tokens?: number; cost_micro_cents?: number; fallback_used?: boolean; tool_calls?: number; physical_attempts?: number; provider_request_id_sha256?: string; physical_attempt?: number; stream_ordinal?: number; tool_name?: string; outcome_code?: string; workload?: string; wall_clock_ms?: number; cold_container_start_ms?: number; restore_ms?: number; checkpoint_ms?: number; active_cpu_ms?: number; uploaded_bytes?: number; llm_calls?: number; instance_type?: string; failure_code?: string };
	type StellaTelemetryDevStreamV1Record = { schema_version: number; event_id: string; occurred_at_ms: number; ingested_at_ms: number; project: string; environment: string; source: string; release?: string; installation_id_sha256?: string; owner_id_sha256: string; principal_kind: string; event_type: string; component?: string; phase?: string; duration_ms?: number; exit_code?: number; reason_code?: string; severity?: string; error_class?: string; error_code?: string; fingerprint?: string; recovered?: boolean; metric?: string; outcome?: string; provider?: string; model?: string; response_model?: string; agent_type?: string; success?: boolean; stop_reason?: string; input_tokens?: number; output_tokens?: number; cached_input_tokens?: number; cache_write_input_tokens?: number; reasoning_tokens?: number; total_tokens?: number; cost_micro_cents?: number; fallback_used?: boolean; tool_calls?: number; physical_attempts?: number; provider_request_id_sha256?: string; physical_attempt?: number; stream_ordinal?: number; tool_name?: string; outcome_code?: string; workload?: string; wall_clock_ms?: number; cold_container_start_ms?: number; restore_ms?: number; checkpoint_ms?: number; active_cpu_ms?: number; uploaded_bytes?: number; llm_calls?: number; instance_type?: string; failure_code?: string };
	interface ProductionEnv {
		TELEMETRY_RATE_LIMITER: RateLimit;
		ENVIRONMENT: "production";
		STELLA_CONVEX_SITE_URL: "https://benevolent-minnow-586.convex.site";
		ENABLE_SERVER_BEARER: "1";
		TELEMETRY_PSEUDONYM_KEY: string;
		TELEMETRY_SERVER_SECRET: string;
		CONVEX_LOG_STREAM_SECRET: string;
		EVENTS_PIPELINE: import("cloudflare:pipelines").Pipeline<Cloudflare.StellaTelemetryProdStreamV1Record>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "STELLA_CONVEX_SITE_URL" | "ENABLE_SERVER_BEARER" | "TELEMETRY_PSEUDONYM_KEY" | "TELEMETRY_SERVER_SECRET" | "CONVEX_LOG_STREAM_SECRET">> {}
}
