/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 11e68c8a4e568a7c93af4ae96100171b)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	X_BOT_USERNAME: string;
	X_BOT_USER_ID: string;
	X_BOT_PROMOTER_USERNAMES: string;
	X_BOT_MODEL: string;
	X_BOT_DRY_RUN: string;
	X_BOT_API_KEY: string;
	X_BOT_API_SECRET: string;
	X_BOT_ACCESS_TOKEN: string;
	X_BOT_ACCESS_TOKEN_SECRET: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "X_BOT_USERNAME" | "X_BOT_USER_ID" | "X_BOT_PROMOTER_USERNAMES" | "X_BOT_MODEL" | "X_BOT_DRY_RUN" | "X_BOT_API_KEY" | "X_BOT_API_SECRET" | "X_BOT_ACCESS_TOKEN" | "X_BOT_ACCESS_TOKEN_SECRET" | "OPENAI_API_KEY">> {}
}
declare module "*.woff" {
	const value: ArrayBuffer;
	export default value;
}