import { describe, expect, test } from "bun:test";
import golden from "./general-agent-prompt-golden.json" with { type: "json" };
import { GENERAL_AGENT_PROMPT_CASES } from "./general-agent-prompt-cases.js";
import { buildGeneralAgentPrompt } from "./general-agent-prompt.js";

const goldenPrompts = golden as Record<string, string>;

describe("general agent prompt", () => {
  // The golden was generated by
  // `scripts/generate-general-agent-prompt-golden.mjs` against the container
  // executor's `CLOUD_GENERAL_PROMPT` before this module existed. Byte
  // equality here is the whole guarantee that moving the prompt into a
  // workerd-safe module changed nothing the model reads.
  for (const testCase of GENERAL_AGENT_PROMPT_CASES) {
    test(`materialized renders the pinned bytes: ${testCase.label}`, () => {
      const rendered = buildGeneralAgentPrompt({
        workspace: "materialized",
        office: testCase.office,
        ...(testCase.drive ? { drive: testCase.drive } : {}),
        ...(testCase.skills ? { skills: testCase.skills } : {}),
      });
      expect(rendered).toBe(goldenPrompts[testCase.label]!);
    });
  }

  test("the golden covers every representative case", () => {
    expect(Object.keys(goldenPrompts).sort()).toEqual(
      GENERAL_AGENT_PROMPT_CASES.map((testCase) => testCase.label).sort(),
    );
  });

  test("lazy drops the on-disk drive claims and says the world restores on first use", () => {
    const lazy = buildGeneralAgentPrompt({ workspace: "lazy", office: true });
    expect(lazy).not.toContain("is the user's drive.");
    expect(lazy).not.toContain("already on disk");
    expect(lazy).toContain("Nothing is on disk yet.");
    expect(lazy).toContain(
      "restore this world and synchronize the user's drive into it the first time you call one",
    );
  });

  test("lazy differs from an undescribed materialized world by exactly that sentence", () => {
    const lazy = buildGeneralAgentPrompt({ workspace: "lazy", office: true });
    const materialized = buildGeneralAgentPrompt({
      workspace: "materialized",
      office: true,
    });
    const [lazyHead, lazyTail] = lazy.split(
      "\n\nNothing is on disk yet.",
    ) as [string, string];
    const marker = "\n\n/workspace/world/stella is the editable source tree";
    expect(lazyTail.slice(lazyTail.indexOf(marker))).toBe(
      materialized.slice(materialized.indexOf(marker)),
    );
    expect(lazyHead).toBe(materialized.slice(0, materialized.indexOf(marker)));
  });

  test("lazy still carries the skill catalog and its bounds", () => {
    const withSkills = GENERAL_AGENT_PROMPT_CASES.find(
      (testCase) => testCase.label === "office-and-skills",
    )!;
    const lazy = buildGeneralAgentPrompt({
      workspace: "lazy",
      office: withSkills.office,
      skills: withSkills.skills!,
    });
    expect(lazy).toContain("version-pinned cloud skills for this turn");
    expect(() =>
      buildGeneralAgentPrompt({
        workspace: "lazy",
        office: false,
        skills: {
          ...withSkills.skills!,
          entries: Array.from({ length: 21 }, () => withSkills.skills!.entries[0]!),
        },
      }),
    ).toThrow("Cloud skill catalog exceeded its runtime bound.");
  });

  test("lazy rejects a skill root outside the pinned sandbox path", () => {
    expect(() =>
      buildGeneralAgentPrompt({
        workspace: "lazy",
        office: false,
        skills: {
          loadedAt: 1,
          root: "/tmp/stella-cloud-skills",
          entries: [
            {
              skillId: "skill-1",
              slug: "calendar",
              name: "Calendar",
              description: "Manage the calendar",
              versionId: "version-7",
              revision: 7,
              root: "/workspace/world/drive",
              allowedToolNames: [],
            },
          ],
        },
      }),
    ).toThrow("Cloud skill descriptor was invalid.");
  });
});
