name = "canvas-share"
main = "src/index.ts"
compatibility_date = "2025-07-01"

[[r2_buckets]]
binding = "SHARES_BUCKET"
bucket_name = "stella-canvas-shares"

[vars]

SHARES_DISABLED = ""

[[routes]]
pattern = "stellashare.app"
custom_domain = true

[observability]
enabled = true
