/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false` (hash: eab4bea5ae49d9030e8a4a7e05b66718)
interface __BaseEnv_Env {
	CONFIG_SNAPSHOT: KVNamespace;
	OWNER_ENFORCEMENT: KVNamespace;
	ASN_POLICY: KVNamespace;
	USAGE_QUEUE: Queue;
	ANON_IP_LIMITER: RateLimit;
	ENVIRONMENT: "production" | "development";
	STELLA_CONVEX_SITE_URL: "https://intent-jackal-330.convex.site" | "https://outgoing-bulldog-865.convex.site";
	CAPABILITY_JWKS: "{\"keys\":[{\"kid\":\"convex-prod-1\",\"issuer\":\"stella-convex\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"LSAu5q_qmUxnER3kfeTUc61NiBoO_A8nk7srI9-EBNg\",\"y\":\"iK4eBIPxte1DlIdQLsLSVCCMapC5nBF-y6pTRSnDkvc\",\"alg\":\"ES256\",\"use\":\"sig\"}},{\"kid\":\"builder-prod-1\",\"issuer\":\"stella-cloud-builder\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"7OPXbcbubpfZqHAZEptNA8Bu1w9Y5D0pq547cg8rYuo\",\"y\":\"tv8_giBW3W4shXI5YPuZMneKHs22dSncE41399_mEmI\",\"alg\":\"ES256\",\"use\":\"sig\"}}]}" | "{\"keys\":[{\"kid\":\"convex-1\",\"issuer\":\"stella-convex\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"z3UW7w02DZv-HzQqRwzPTEYN3PIO9hIxjcj7d8DRo3E\",\"y\":\"oGXA5AT_zPGJrJxcv5UgwyV2fhC4mQEAGckZEmn15W0\",\"alg\":\"ES256\",\"use\":\"sig\"}},{\"kid\":\"builder-1\",\"issuer\":\"stella-cloud-builder\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"_zTj5c7FMbjcMng9baQbQRXtkHak6jk4-1boqSnt59A\",\"y\":\"tR-kttYxzHOPR__VorAqBes7AkaI9uvAiyuM7h7DMEk\",\"alg\":\"ES256\",\"use\":\"sig\"}},{\"kid\":\"builder-bn118-1\",\"issuer\":\"stella-cloud-builder\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"3B2uhLMZ0nFNovFPfyHOqiVeXac4vJO0YhR1F7U1xQc\",\"y\":\"_vW3crzH0DnvV5yjUqvxa9qH5_lygAfXR7FWiI7MLAA\",\"alg\":\"ES256\",\"use\":\"sig\"}}]}";
	OPENROUTER_API_KEY: string;
	FIREWORKS_API_KEY: string;
	DEEPSEEK_API_KEY: string;
	CROF_API_KEY: string;
	WAFER_API_KEY: string;
	XAI_API_KEY: string;
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	GOOGLE_AI_API_KEY: string;
	META_MODEL_API_KEY: string;
	GATEWAY_SERVICE_SECRET: string;
	STELLA_RELAY_PROBE_SECRET: string;
	CAPABILITY_LEDGER: DurableObjectNamespace<import("./src/index").CapabilityLedger>;
	OWNER_CAPABILITY_LEDGER: DurableObjectNamespace<import("./src/index").OwnerCapabilityLedger>;
	OWNER_RELAY_GATE: DurableObjectNamespace<import("./src/index").OwnerRelayGate>;
	NETWORK_GATE: DurableObjectNamespace<import("./src/index").NetworkGate>;
	TIER_BUDGET: DurableObjectNamespace<import("./src/index").TierBudget>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CapabilityLedger" | "OwnerRelayGate" | "NetworkGate" | "TierBudget" | "OwnerCapabilityLedger";
	}
	interface ProductionEnv {
		CONFIG_SNAPSHOT: KVNamespace;
		OWNER_ENFORCEMENT: KVNamespace;
		ASN_POLICY: KVNamespace;
		USAGE_QUEUE: Queue;
		ANON_IP_LIMITER: RateLimit;
		ENVIRONMENT: "production";
		STELLA_CONVEX_SITE_URL: "https://intent-jackal-330.convex.site";
		CAPABILITY_JWKS: "{\"keys\":[{\"kid\":\"convex-prod-1\",\"issuer\":\"stella-convex\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"LSAu5q_qmUxnER3kfeTUc61NiBoO_A8nk7srI9-EBNg\",\"y\":\"iK4eBIPxte1DlIdQLsLSVCCMapC5nBF-y6pTRSnDkvc\",\"alg\":\"ES256\",\"use\":\"sig\"}},{\"kid\":\"builder-prod-1\",\"issuer\":\"stella-cloud-builder\",\"jwk\":{\"kty\":\"EC\",\"crv\":\"P-256\",\"x\":\"7OPXbcbubpfZqHAZEptNA8Bu1w9Y5D0pq547cg8rYuo\",\"y\":\"tv8_giBW3W4shXI5YPuZMneKHs22dSncE41399_mEmI\",\"alg\":\"ES256\",\"use\":\"sig\"}}]}";
		OPENROUTER_API_KEY: string;
		FIREWORKS_API_KEY: string;
		DEEPSEEK_API_KEY: string;
		CROF_API_KEY: string;
		WAFER_API_KEY: string;
		XAI_API_KEY: string;
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		GOOGLE_AI_API_KEY: string;
		META_MODEL_API_KEY: string;
		GATEWAY_SERVICE_SECRET: string;
		STELLA_RELAY_PROBE_SECRET: string;
		CAPABILITY_LEDGER: DurableObjectNamespace<import("./src/index").CapabilityLedger>;
		OWNER_CAPABILITY_LEDGER: DurableObjectNamespace<import("./src/index").OwnerCapabilityLedger>;
		OWNER_RELAY_GATE: DurableObjectNamespace<import("./src/index").OwnerRelayGate>;
		NETWORK_GATE: DurableObjectNamespace<import("./src/index").NetworkGate>;
		TIER_BUDGET: DurableObjectNamespace<import("./src/index").TierBudget>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "STELLA_CONVEX_SITE_URL" | "CAPABILITY_JWKS" | "OPENROUTER_API_KEY" | "FIREWORKS_API_KEY" | "DEEPSEEK_API_KEY" | "CROF_API_KEY" | "WAFER_API_KEY" | "XAI_API_KEY" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "GOOGLE_AI_API_KEY" | "META_MODEL_API_KEY" | "GATEWAY_SERVICE_SECRET" | "STELLA_RELAY_PROBE_SECRET">> {}
}
