/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false` (hash: 0d44398052f70c32f163581db3135d42)
interface __BaseEnv_Env {
	BROWSER_PROFILES: R2Bucket;
	BROWSER: BrowserRun;
	STELLA_DEPLOYMENT_IDENTITY: "basic-nightingale-118" | "dev";
	BROWSER_KEEP_ALIVE_MS: "600000";
	BROWSER_LIVE_VIEW_TTL_MS: "300000";
	BROWSER_HANDOFF_TIMEOUT_MS: "600000";
	DEVICE_CODE_FIXTURE_ORIGIN?: "https://stella-v2-device-code-fixture-basic-nightingale-118.lolruuxi.workers.dev";
	BROWSER_PROFILE_KEK_V1: string;
	BROWSER_PROFILE_SESSIONS: DurableObjectNamespace<import("./src/index").BrowserProfileSession>;
	DEVICE_CODE_FIXTURE?: Service /* entrypoint DeviceCodeFixtureService from stella-v2-device-code-fixture-basic-nightingale-118 */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BrowserProfileSession";
	}
	interface Bn118Env {
		BROWSER_PROFILES: R2Bucket;
		BROWSER: BrowserRun;
		STELLA_DEPLOYMENT_IDENTITY: "basic-nightingale-118";
		BROWSER_KEEP_ALIVE_MS: "600000";
		BROWSER_LIVE_VIEW_TTL_MS: "300000";
		BROWSER_HANDOFF_TIMEOUT_MS: "600000";
		DEVICE_CODE_FIXTURE_ORIGIN: "https://stella-v2-device-code-fixture-basic-nightingale-118.lolruuxi.workers.dev";
		BROWSER_PROFILE_KEK_V1: string;
		BROWSER_PROFILE_SESSIONS: DurableObjectNamespace<import("./src/index").BrowserProfileSession>;
		DEVICE_CODE_FIXTURE: Service /* entrypoint DeviceCodeFixtureService from stella-v2-device-code-fixture-basic-nightingale-118 */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STELLA_DEPLOYMENT_IDENTITY" | "BROWSER_KEEP_ALIVE_MS" | "BROWSER_LIVE_VIEW_TTL_MS" | "BROWSER_HANDOFF_TIMEOUT_MS" | "DEVICE_CODE_FIXTURE_ORIGIN" | "BROWSER_PROFILE_KEK_V1">> {}
}
