const {
  withInfoPlist,
  withDangerousMod,
  withXcodeProject,
  IOSConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const CAR_DELEGATE = "StellaCarSceneDelegate";
const CAR_SCENE_CONFIG_NAME = "Stella-CarPlay";
const PHONE_DELEGATE = "StellaPhoneSceneDelegate";
const PHONE_SCENE_CONFIG_NAME = "Stella-Phone";

const CARPLAY_SCENE_ROLE = "CPTemplateApplicationSceneSessionRoleApplication";
const PHONE_SCENE_ROLE = "UIWindowSceneSessionRoleApplication";

const CAR_HEADER_CONTENTS = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
#import <UIKit/UIKit.h>
#import <CarPlay/CarPlay.h>

@interface ${CAR_DELEGATE} : UIResponder <CPTemplateApplicationSceneDelegate>
@end
`;

const CAR_IMPL_CONTENTS = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
#import "${CAR_DELEGATE}.h"
#import "RNCarPlay.h"

static NSString * const StellaCarPlayDiagnosticsKey = @"StellaCarPlayDiagnostics";

static void StellaCarPlayLog(NSString *format, ...) {
  va_list args;
  va_start(args, format);
  NSString *message = [[NSString alloc] initWithFormat:format arguments:args];
  va_end(args);

  NSLog(@"[carplay] %@", message);

  NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
  NSArray<NSString *> *existing = [defaults stringArrayForKey:StellaCarPlayDiagnosticsKey] ?: @[];
  NSMutableArray<NSString *> *next = [existing mutableCopy];
  NSString *line = [NSString stringWithFormat:@"%@ %@", [NSDate date], message];
  [next addObject:line];
  while (next.count > 80) {
    [next removeObjectAtIndex:0];
  }
  [defaults setObject:next forKey:StellaCarPlayDiagnosticsKey];
  [defaults synchronize];
}

static CPInterfaceController *gInterfaceController = nil;
static CPWindow *gCarWindow = nil;
static CPListTemplate *gPlaceholderTemplate = nil;
static CPListItem *gPlaceholderItem = nil;
static NSInteger gTakeoverRetries = 0;

static void StellaCarPlayRetryTakeover(NSString *reason) {
  if (!gInterfaceController) {
    StellaCarPlayLog(@"retry(%@): no interface controller — CarPlay disconnected", reason);
    return;
  }
  CPTemplate *root = gInterfaceController.rootTemplate;
  if (root != nil && root != (CPTemplate *)gPlaceholderTemplate) {
    StellaCarPlayLog(@"retry(%@): JS takeover complete (root=%@)", reason, NSStringFromClass([root class]));
    return;
  }
  gTakeoverRetries += 1;
  StellaCarPlayLog(@"retry(%@): root still native placeholder (attempt %ld) — re-emitting didConnect",
                   reason, (long)gTakeoverRetries);
  if (gPlaceholderItem != nil) {
    if (gTakeoverRetries >= 4) {
      [gPlaceholderItem setDetailText:@"Still connecting — open Stella on your iPhone"];
    } else {
      [gPlaceholderItem setDetailText:@"Connecting to Stella..."];
    }
  }

  [RNCarPlay connectWithInterfaceController:gInterfaceController window:gCarWindow];
}

static void StellaCarPlayScheduleTakeoverWatchdog(void) {

  for (NSNumber *delay in @[@2.0, @6.0, @12.0, @20.0]) {
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delay.doubleValue * NSEC_PER_SEC)),
                   dispatch_get_main_queue(), ^{
      StellaCarPlayRetryTakeover([NSString stringWithFormat:@"watchdog+%.0fs", delay.doubleValue]);
    });
  }
}

static void StellaCarPlayInstallPlaceholder(CPInterfaceController *interfaceController) {
  if (!interfaceController) {
    StellaCarPlayLog(@"missing CPInterfaceController; cannot install native placeholder");
    return;
  }

  CPListItem *talkItem = [[CPListItem alloc] initWithText:@"Talk to Stella"
                                               detailText:@"Starting voice mode..."
                                                    image:nil
                                 showsDisclosureIndicator:NO];

  talkItem.handler = ^(id<CPSelectableListItem> item, dispatch_block_t completionBlock) {
    StellaCarPlayLog(@"native placeholder row tapped");
    StellaCarPlayRetryTakeover(@"tap");
    completionBlock();
  };
  CPListSection *section = [[CPListSection alloc] initWithItems:@[talkItem]
                                                        header:nil
                                             sectionIndexTitle:nil];
  CPListTemplate *template = [[CPListTemplate alloc] initWithTitle:@"Stella" sections:@[section]];
  gPlaceholderItem = talkItem;
  gPlaceholderTemplate = template;
  gTakeoverRetries = 0;

  [interfaceController setRootTemplate:template animated:NO completion:^(BOOL done, NSError * _Nullable error) {
    StellaCarPlayLog(@"native placeholder setRootTemplate done=%@ error=%@",
                     done ? @"YES" : @"NO",
                     error.localizedDescription ?: @"none");
  }];
}

@implementation ${CAR_DELEGATE}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
   didConnectInterfaceController:(CPInterfaceController *)interfaceController {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didConnect modern selector window=%@ bounds=%@",
                     templateApplicationScene.carWindow ? @"YES" : @"NO",
                     templateApplicationScene.carWindow ? NSStringFromCGRect(templateApplicationScene.carWindow.bounds) : @"nil");
    gInterfaceController = interfaceController;
    gCarWindow = templateApplicationScene.carWindow;
    StellaCarPlayInstallPlaceholder(interfaceController);
    [RNCarPlay connectWithInterfaceController:interfaceController
                                      window:templateApplicationScene.carWindow];
    StellaCarPlayLog(@"forwarded connect to RNCarPlay");
    StellaCarPlayScheduleTakeoverWatchdog();
  });
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
didDisconnectInterfaceController:(CPInterfaceController *)interfaceController {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didDisconnect modern selector");
    gInterfaceController = nil;
    gCarWindow = nil;
    gPlaceholderTemplate = nil;
    gPlaceholderItem = nil;
    [RNCarPlay disconnect];
  });
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
   didConnectInterfaceController:(CPInterfaceController *)interfaceController
                        toWindow:(CPWindow *)window {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didConnect legacy selector window=%@ bounds=%@",
                     window ? @"YES" : @"NO",
                     window ? NSStringFromCGRect(window.bounds) : @"nil");
    gInterfaceController = interfaceController;
    gCarWindow = window;
    StellaCarPlayInstallPlaceholder(interfaceController);
    [RNCarPlay connectWithInterfaceController:interfaceController window:window];
    StellaCarPlayLog(@"forwarded legacy connect to RNCarPlay");
    StellaCarPlayScheduleTakeoverWatchdog();
  });
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
didDisconnectInterfaceController:(CPInterfaceController *)interfaceController
                      fromWindow:(CPWindow *)window {
  dispatch_async(dispatch_get_main_queue(), ^{
    StellaCarPlayLog(@"didDisconnect legacy selector");
    gInterfaceController = nil;
    gCarWindow = nil;
    gPlaceholderTemplate = nil;
    gPlaceholderItem = nil;
    [RNCarPlay disconnect];
  });
}

@end
`;

const PHONE_DELEGATE_SWIFT = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
import UIKit

@objc(${PHONE_DELEGATE})
class ${PHONE_DELEGATE}: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = UIApplication.shared.delegate,
          let appWindow = appDelegate.window,
          let window = appWindow
    else { return }
    window.windowScene = windowScene
    self.window = window
    window.makeKeyAndVisible()
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    UIApplication.shared.delegate?.application?(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }
}
`;

const withCarPlaySceneManifest = (config) =>
  withInfoPlist(config, (cfg) => {
    const existing =
      cfg.modResults.UIApplicationSceneManifest &&
      typeof cfg.modResults.UIApplicationSceneManifest === "object"
        ? cfg.modResults.UIApplicationSceneManifest
        : {};
    const existingConfigs =
      existing.UISceneConfigurations &&
      typeof existing.UISceneConfigurations === "object"
        ? existing.UISceneConfigurations
        : {};

    cfg.modResults.UIApplicationSceneManifest = {
      ...existing,
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        ...existingConfigs,
        [PHONE_SCENE_ROLE]: [
          {
            UISceneClassName: "UIWindowScene",
            UISceneConfigurationName: PHONE_SCENE_CONFIG_NAME,
            UISceneDelegateClassName: PHONE_DELEGATE,
          },
        ],
        [CARPLAY_SCENE_ROLE]: [
          {
            UISceneClassName: "CPTemplateApplicationScene",
            UISceneConfigurationName: CAR_SCENE_CONFIG_NAME,
            UISceneDelegateClassName: CAR_DELEGATE,
          },
        ],
      },
    };
    return cfg;
  });

const withSceneDelegateSources = (config) =>
  withDangerousMod(config, [
    "ios",
    (cfg) => {
      const appName = cfg.modRequest.projectName;
      const dir = path.join(cfg.modRequest.platformProjectRoot, appName);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${CAR_DELEGATE}.h`), CAR_HEADER_CONTENTS);
      fs.writeFileSync(path.join(dir, `${CAR_DELEGATE}.m`), CAR_IMPL_CONTENTS);
      fs.writeFileSync(
        path.join(dir, `${PHONE_DELEGATE}.swift`),
        PHONE_DELEGATE_SWIFT,
      );
      return cfg;
    },
  ]);

const withSceneDelegateBuildFiles = (config) =>
  withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const appName = cfg.modRequest.projectName;

    for (const rel of [
      `${appName}/${CAR_DELEGATE}.m`,
      `${appName}/${PHONE_DELEGATE}.swift`,
    ]) {
      if (!project.hasFile(rel)) {
        IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
          filepath: rel,
          groupName: appName,
          project,
        });
      }
    }
    return cfg;
  });

module.exports = function withStellaCarPlay(config) {
  config = withCarPlaySceneManifest(config);
  config = withSceneDelegateSources(config);
  config = withSceneDelegateBuildFiles(config);
  return config;
};
