/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false` (hash: eb0a7af0711c4592bd566a1e6472dfd2)
interface __BaseEnv_Env {
	APP_ROUTES: KVNamespace;
	APP_BUILDS: R2Bucket;
	BACKUP_BUCKET: R2Bucket;
	AGENT_HOME: R2Bucket;
	CONVERSATION_ARCHIVE: R2Bucket;
	LOADER: WorkerLoader;
	TELEMETRY_ENVIRONMENT: "development";
	SANDBOX_TRANSPORT: "rpc";
	TURN_TIMEOUT_MS: "900000";
	SANDBOX_IDLE_TIMEOUT_MS: "600000";
	APPS_HOST_BASE_URL: "https://stella-v2-apps-host-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-apps-host-dev.lolruuxi.workers.dev";
	TRUSTED_APPS_HOST_BASE_URL: "https://stella-v2-apps-auth-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-apps-auth-dev.lolruuxi.workers.dev";
	STELLA_CONVEX_SITE_URL: "https://basic-nightingale-118.convex.site" | "https://outgoing-bulldog-865.convex.site";
	STELLA_CONVEX_CLOUD_URL: "https://basic-nightingale-118.convex.cloud" | "https://outgoing-bulldog-865.convex.cloud";
	ENABLE_DEV_ACCEPTANCE_PROBES: "1";
	STELLA_DEPLOYMENT_IDENTITY: "preview:basic-nightingale-118" | "dev:outgoing-bulldog-865";
	BUILDER_SERVICE_SECRET: string;
	Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
	SANDBOX_SMALL: DurableObjectNamespace<import("./src/index").SandboxSmall>;
	APP_BUILD_SANDBOX: DurableObjectNamespace<import("./src/index").AppBuildSandbox>;
	BUILD_SESSIONS: DurableObjectNamespace<import("./src/index").BuildSession>;
	ORCHESTRATOR_SESSIONS: DurableObjectNamespace<import("./src/index").OrchestratorSession>;
	OWNER_TRANSFER_COORDINATORS: DurableObjectNamespace<import("./src/index").OwnerTransferCoordinator>;
	DEVICE_PRESENCE: DurableObjectNamespace<import("./src/index").DevicePresence>;
	TELEMETRY: Service /* entrypoint TelemetryService from stella-v2-telemetry-dev */;
	BROWSER_GATEWAY: Fetcher /* stella-v2-browser-gateway-basic-nightingale-118 */ | Fetcher /* stella-v2-browser-gateway-dev */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Sandbox" | "BuildSession" | "OrchestratorSession" | "SandboxSmall" | "OwnerTransferCoordinator" | "AppBuildSandbox" | "DevicePresence";
	}
	interface Bn118Env {
		APP_ROUTES: KVNamespace;
		APP_BUILDS: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		AGENT_HOME: R2Bucket;
		CONVERSATION_ARCHIVE: R2Bucket;
		LOADER: WorkerLoader;
		TELEMETRY_ENVIRONMENT: "development";
		SANDBOX_TRANSPORT: "rpc";
		TURN_TIMEOUT_MS: "900000";
		SANDBOX_IDLE_TIMEOUT_MS: "600000";
		APPS_HOST_BASE_URL: "https://stella-v2-apps-host-basic-nightingale-118.lolruuxi.workers.dev";
		TRUSTED_APPS_HOST_BASE_URL: "https://stella-v2-apps-auth-basic-nightingale-118.lolruuxi.workers.dev";
		STELLA_CONVEX_SITE_URL: "https://basic-nightingale-118.convex.site";
		STELLA_CONVEX_CLOUD_URL: "https://basic-nightingale-118.convex.cloud";
		ENABLE_DEV_ACCEPTANCE_PROBES: "1";
		STELLA_DEPLOYMENT_IDENTITY: "preview:basic-nightingale-118";
		BUILDER_SERVICE_SECRET: string;
		Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
		SANDBOX_SMALL: DurableObjectNamespace<import("./src/index").SandboxSmall>;
		APP_BUILD_SANDBOX: DurableObjectNamespace<import("./src/index").AppBuildSandbox>;
		BUILD_SESSIONS: DurableObjectNamespace<import("./src/index").BuildSession>;
		ORCHESTRATOR_SESSIONS: DurableObjectNamespace<import("./src/index").OrchestratorSession>;
		OWNER_TRANSFER_COORDINATORS: DurableObjectNamespace<import("./src/index").OwnerTransferCoordinator>;
		DEVICE_PRESENCE: DurableObjectNamespace<import("./src/index").DevicePresence>;
		TELEMETRY: Service /* entrypoint TelemetryService from stella-v2-telemetry-dev */;
		BROWSER_GATEWAY: Fetcher /* stella-v2-browser-gateway-basic-nightingale-118 */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELEMETRY_ENVIRONMENT" | "SANDBOX_TRANSPORT" | "TURN_TIMEOUT_MS" | "SANDBOX_IDLE_TIMEOUT_MS" | "APPS_HOST_BASE_URL" | "TRUSTED_APPS_HOST_BASE_URL" | "STELLA_CONVEX_SITE_URL" | "STELLA_CONVEX_CLOUD_URL" | "ENABLE_DEV_ACCEPTANCE_PROBES" | "STELLA_DEPLOYMENT_IDENTITY" | "BUILDER_SERVICE_SECRET">> {}
}
