/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.wrangler/types/wrangler.json --env= --include-runtime=false` (hash: f223f2fe61284e68c89ad0eccc6b8524)
interface __BaseEnv_Env {
	APP_ROUTES: KVNamespace;
	ASN_POLICY: KVNamespace;
	APP_BUILDS: R2Bucket;
	BACKUP_BUCKET: R2Bucket;
	AGENT_HOME: R2Bucket;
	CONVERSATION_ARCHIVE: R2Bucket;
	WORLDS_BUCKET: R2Bucket;
	TURN_OUTBOX: Queue;
	LOADER: WorkerLoader;
	TELEMETRY_ENVIRONMENT: "development" | "production";
	SANDBOX_TRANSPORT: "rpc";
	TURN_TIMEOUT_MS: "900000";
	SANDBOX_IDLE_TIMEOUT_MS: "600000";
	APPS_HOST_BASE_URL: "https://stella-v2-apps-host-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-apps-host-prod.lolruuxi.workers.dev" | "https://stella-v2-apps-host-dev.lolruuxi.workers.dev";
	TRUSTED_APPS_HOST_BASE_URL: "https://stella-v2-apps-auth-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-apps-auth-prod.lolruuxi.workers.dev" | "https://stella-v2-apps-auth-dev.lolruuxi.workers.dev";
	STELLA_CONVEX_SITE_URL: "https://basic-nightingale-118.convex.site" | "https://intent-jackal-330.convex.site" | "https://outgoing-bulldog-865.convex.site";
	STELLA_CONVEX_CLOUD_URL: "https://basic-nightingale-118.convex.cloud" | "https://intent-jackal-330.convex.cloud" | "https://outgoing-bulldog-865.convex.cloud";
	ENABLE_DEV_ACCEPTANCE_PROBES?: "1";
	STELLA_DEPLOYMENT_IDENTITY: "preview:basic-nightingale-118" | "prod:intent-jackal-330" | "dev:outgoing-bulldog-865";
	MODEL_GATEWAY_URL: "https://stella-v2-model-gateway-dev.lolruuxi.workers.dev" | "https://stella-v2-model-gateway.lolruuxi.workers.dev";
	CAPABILITY_SIGNING_KID: "builder-bn118-1" | "builder-prod-1" | "builder-1";
	CLOUD_BUILDER_PUBLIC_URL: "https://stella-v2-cloud-builder-basic-nightingale-118.lolruuxi.workers.dev" | "https://stella-v2-cloud-builder-prod.lolruuxi.workers.dev" | "https://stella-v2-cloud-builder-dev.lolruuxi.workers.dev";
	BUILDER_SERVICE_SECRET: string;
	META_MODEL_API_KEY: string;
	CAPABILITY_SIGNING_KEY: string;
	Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
	SANDBOX_SMALL: DurableObjectNamespace<import("./src/index").SandboxSmall>;
	APP_BUILD_SANDBOX: DurableObjectNamespace<import("./src/index").AppBuildSandbox>;
	BUILD_SESSIONS: DurableObjectNamespace<import("./src/index").BuildSession>;
	ORCHESTRATOR_SESSIONS: DurableObjectNamespace<import("./src/index").OrchestratorSession>;
	OWNER_TRANSFER_COORDINATORS: DurableObjectNamespace<import("./src/index").OwnerTransferCoordinator>;
	OWNER_GATES: DurableObjectNamespace<import("./src/index").OwnerGate>;
	WORLDS: DurableObjectNamespace<import("./src/index").WorldStore>;
	TELEMETRY: Service /* entrypoint TelemetryService from stella-v2-telemetry-dev */ | Service /* entrypoint TelemetryService from stella-v2-telemetry */;
	BROWSER_GATEWAY: Fetcher /* stella-v2-browser-gateway-basic-nightingale-118 */ | Fetcher /* stella-v2-browser-gateway-prod */ | Fetcher /* stella-v2-browser-gateway-dev */;
	MODEL_GATEWAY: Fetcher /* stella-v2-model-gateway-dev */ | Fetcher /* stella-v2-model-gateway */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Sandbox" | "BuildSession" | "OrchestratorSession" | "SandboxSmall" | "OwnerTransferCoordinator" | "AppBuildSandbox" | "OwnerGate" | "WorldStore";
	}
	interface Bn118Env {
		APP_ROUTES: KVNamespace;
		ASN_POLICY: KVNamespace;
		APP_BUILDS: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		AGENT_HOME: R2Bucket;
		CONVERSATION_ARCHIVE: R2Bucket;
		WORLDS_BUCKET: R2Bucket;
		TURN_OUTBOX: Queue;
		LOADER: WorkerLoader;
		TELEMETRY_ENVIRONMENT: "development";
		SANDBOX_TRANSPORT: "rpc";
		TURN_TIMEOUT_MS: "900000";
		SANDBOX_IDLE_TIMEOUT_MS: "600000";
		APPS_HOST_BASE_URL: "https://stella-v2-apps-host-basic-nightingale-118.lolruuxi.workers.dev";
		TRUSTED_APPS_HOST_BASE_URL: "https://stella-v2-apps-auth-basic-nightingale-118.lolruuxi.workers.dev";
		STELLA_CONVEX_SITE_URL: "https://basic-nightingale-118.convex.site";
		STELLA_CONVEX_CLOUD_URL: "https://basic-nightingale-118.convex.cloud";
		ENABLE_DEV_ACCEPTANCE_PROBES: "1";
		STELLA_DEPLOYMENT_IDENTITY: "preview:basic-nightingale-118";
		MODEL_GATEWAY_URL: "https://stella-v2-model-gateway-dev.lolruuxi.workers.dev";
		CAPABILITY_SIGNING_KID: "builder-bn118-1";
		CLOUD_BUILDER_PUBLIC_URL: "https://stella-v2-cloud-builder-basic-nightingale-118.lolruuxi.workers.dev";
		BUILDER_SERVICE_SECRET: string;
		META_MODEL_API_KEY: string;
		CAPABILITY_SIGNING_KEY: string;
		Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
		SANDBOX_SMALL: DurableObjectNamespace<import("./src/index").SandboxSmall>;
		APP_BUILD_SANDBOX: DurableObjectNamespace<import("./src/index").AppBuildSandbox>;
		BUILD_SESSIONS: DurableObjectNamespace<import("./src/index").BuildSession>;
		ORCHESTRATOR_SESSIONS: DurableObjectNamespace<import("./src/index").OrchestratorSession>;
		OWNER_TRANSFER_COORDINATORS: DurableObjectNamespace<import("./src/index").OwnerTransferCoordinator>;
		OWNER_GATES: DurableObjectNamespace<import("./src/index").OwnerGate>;
		WORLDS: DurableObjectNamespace<import("./src/index").WorldStore>;
		TELEMETRY: Service /* entrypoint TelemetryService from stella-v2-telemetry-dev */;
		BROWSER_GATEWAY: Fetcher /* stella-v2-browser-gateway-basic-nightingale-118 */;
		MODEL_GATEWAY: Fetcher /* stella-v2-model-gateway-dev */;
	}
	interface ProductionEnv {
		APP_ROUTES: KVNamespace;
		ASN_POLICY: KVNamespace;
		APP_BUILDS: R2Bucket;
		BACKUP_BUCKET: R2Bucket;
		AGENT_HOME: R2Bucket;
		CONVERSATION_ARCHIVE: R2Bucket;
		WORLDS_BUCKET: R2Bucket;
		TURN_OUTBOX: Queue;
		LOADER: WorkerLoader;
		TELEMETRY_ENVIRONMENT: "production";
		SANDBOX_TRANSPORT: "rpc";
		TURN_TIMEOUT_MS: "900000";
		SANDBOX_IDLE_TIMEOUT_MS: "600000";
		APPS_HOST_BASE_URL: "https://stella-v2-apps-host-prod.lolruuxi.workers.dev";
		TRUSTED_APPS_HOST_BASE_URL: "https://stella-v2-apps-auth-prod.lolruuxi.workers.dev";
		STELLA_CONVEX_SITE_URL: "https://intent-jackal-330.convex.site";
		STELLA_CONVEX_CLOUD_URL: "https://intent-jackal-330.convex.cloud";
		STELLA_DEPLOYMENT_IDENTITY: "prod:intent-jackal-330";
		MODEL_GATEWAY_URL: "https://stella-v2-model-gateway.lolruuxi.workers.dev";
		CAPABILITY_SIGNING_KID: "builder-prod-1";
		CLOUD_BUILDER_PUBLIC_URL: "https://stella-v2-cloud-builder-prod.lolruuxi.workers.dev";
		BUILDER_SERVICE_SECRET: string;
		META_MODEL_API_KEY: string;
		CAPABILITY_SIGNING_KEY: string;
		Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
		SANDBOX_SMALL: DurableObjectNamespace<import("./src/index").SandboxSmall>;
		APP_BUILD_SANDBOX: DurableObjectNamespace<import("./src/index").AppBuildSandbox>;
		BUILD_SESSIONS: DurableObjectNamespace<import("./src/index").BuildSession>;
		ORCHESTRATOR_SESSIONS: DurableObjectNamespace<import("./src/index").OrchestratorSession>;
		OWNER_TRANSFER_COORDINATORS: DurableObjectNamespace<import("./src/index").OwnerTransferCoordinator>;
		OWNER_GATES: DurableObjectNamespace<import("./src/index").OwnerGate>;
		WORLDS: DurableObjectNamespace<import("./src/index").WorldStore>;
		TELEMETRY: Service /* entrypoint TelemetryService from stella-v2-telemetry */;
		BROWSER_GATEWAY: Fetcher /* stella-v2-browser-gateway-prod */;
		MODEL_GATEWAY: Fetcher /* stella-v2-model-gateway */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELEMETRY_ENVIRONMENT" | "SANDBOX_TRANSPORT" | "TURN_TIMEOUT_MS" | "SANDBOX_IDLE_TIMEOUT_MS" | "APPS_HOST_BASE_URL" | "TRUSTED_APPS_HOST_BASE_URL" | "STELLA_CONVEX_SITE_URL" | "STELLA_CONVEX_CLOUD_URL" | "ENABLE_DEV_ACCEPTANCE_PROBES" | "STELLA_DEPLOYMENT_IDENTITY" | "MODEL_GATEWAY_URL" | "CAPABILITY_SIGNING_KID" | "CLOUD_BUILDER_PUBLIC_URL" | "BUILDER_SERVICE_SECRET" | "META_MODEL_API_KEY" | "CAPABILITY_SIGNING_KEY">> {}
}
