/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as account_billing_purge from "../account_billing_purge.js";
import type * as account_deletion from "../account_deletion.js";
import type * as account_external_media from "../account_external_media.js";
import type * as account_external_media_store from "../account_external_media_store.js";
import type * as account_tts_purge from "../account_tts_purge.js";
import type * as admin_deletes from "../admin_deletes.js";
import type * as agent_agents from "../agent/agents.js";
import type * as agent_hooks from "../agent/hooks.js";
import type * as agent_invoke from "../agent/invoke.js";
import type * as agent_local_runtime from "../agent/local_runtime.js";
import type * as agent_model from "../agent/model.js";
import type * as agent_model_execution from "../agent/model_execution.js";
import type * as agent_model_failover from "../agent/model_failover.js";
import type * as agent_model_resolver from "../agent/model_resolver.js";
import type * as agent_prompt_builder from "../agent/prompt_builder.js";
import type * as agent_tool_schemas from "../agent/tool_schemas.js";
import type * as agent_event_ownership from "../agent_event_ownership.js";
import type * as ai_proxy_data from "../ai_proxy_data.js";
import type * as alerts from "../alerts.js";
import type * as anon_cleanup from "../anon_cleanup.js";
import type * as app_integrity from "../app_integrity.js";
import type * as app_integrity_node from "../app_integrity_node.js";
import type * as auth from "../auth.js";
import type * as auth_account_deletion from "../auth_account_deletion.js";
import type * as auth_migration from "../auth_migration.js";
import type * as automation_index from "../automation/index.js";
import type * as automation_runner from "../automation/runner.js";
import type * as billing from "../billing.js";
import type * as billing_measurement from "../billing_measurement.js";
import type * as billing_migrations from "../billing_migrations.js";
import type * as capability_contract from "../capability_contract.js";
import type * as channels_connector_delivery from "../channels/connector_delivery.js";
import type * as channels_connector_media from "../channels/connector_media.js";
import type * as channels_connector_media_types from "../channels/connector_media_types.js";
import type * as channels_connector_privacy from "../channels/connector_privacy.js";
import type * as channels_connector_turn_payloads from "../channels/connector_turn_payloads.js";
import type * as channels_execution_policy from "../channels/execution_policy.js";
import type * as cloud_agent_dispatch from "../cloud_agent_dispatch.js";
import type * as cloud_agent_home from "../cloud_agent_home.js";
import type * as cloud_apps from "../cloud_apps.js";
import type * as cloud_browser from "../cloud_browser.js";
import type * as cloud_conversation_edits from "../cloud_conversation_edits.js";
import type * as cloud_drive from "../cloud_drive.js";
import type * as cloud_drive_node from "../cloud_drive_node.js";
import type * as cloud_engines from "../cloud_engines.js";
import type * as cloud_home_context from "../cloud_home_context.js";
import type * as cloud_integration_catalog from "../cloud_integration_catalog.js";
import type * as cloud_memory from "../cloud_memory.js";
import type * as cloud_memory_lifecycle from "../cloud_memory_lifecycle.js";
import type * as cloud_outbox from "../cloud_outbox.js";
import type * as cloud_projects from "../cloud_projects.js";
import type * as cloud_purge from "../cloud_purge.js";
import type * as cloud_schedule from "../cloud_schedule.js";
import type * as cloud_skills from "../cloud_skills.js";
import type * as cloudflare_tunnels from "../cloudflare_tunnels.js";
import type * as component_r2_deletion from "../component_r2_deletion.js";
import type * as composio_native_dispatch from "../composio_native_dispatch.js";
import type * as composio_purge from "../composio_purge.js";
import type * as composio_purge_store from "../composio_purge_store.js";
import type * as composio_session_cleanup from "../composio_session_cleanup.js";
import type * as composio_session_dispatch from "../composio_session_dispatch.js";
import type * as conversations from "../conversations.js";
import type * as crons from "../crons.js";
import type * as data_asset_metadata from "../data/asset_metadata.js";
import type * as data_attachments from "../data/attachments.js";
import type * as data_canvas_shares from "../data/canvas_shares.js";
import type * as data_canvas_shares_actions from "../data/canvas_shares_actions.js";
import type * as data_desktop_releases from "../data/desktop_releases.js";
import type * as data_emoji_pack_generation from "../data/emoji_pack_generation.js";
import type * as data_emoji_pack_grid from "../data/emoji_pack_grid.js";
import type * as data_emoji_pack_grid_constants from "../data/emoji_pack_grid_constants.js";
import type * as data_emoji_pack_reference_images from "../data/emoji_pack_reference_images.js";
import type * as data_emoji_pack_uploads from "../data/emoji_pack_uploads.js";
import type * as data_emoji_packs from "../data/emoji_packs.js";
import type * as data_fashion from "../data/fashion.js";
import type * as data_integrations from "../data/integrations.js";
import type * as data_preferences from "../data/preferences.js";
import type * as data_secrets from "../data/secrets.js";
import type * as data_secrets_crypto from "../data/secrets_crypto.js";
import type * as data_secrets_rotation from "../data/secrets_rotation.js";
import type * as data_threads from "../data/threads.js";
import type * as data_x_bot from "../data/x_bot.js";
import type * as device_identity from "../device_identity.js";
import type * as dictation_sessions from "../dictation_sessions.js";
import type * as events from "../events.js";
import type * as execution_placement from "../execution_placement.js";
import type * as feedback from "../feedback.js";
import type * as gateway_capabilities from "../gateway_capabilities.js";
import type * as http from "../http.js";
import type * as http_routes_admin from "../http_routes/admin.js";
import type * as http_routes_app_integrity from "../http_routes/app_integrity.js";
import type * as http_routes_apps_sdk from "../http_routes/apps_sdk.js";
import type * as http_routes_cloud_agent from "../http_routes/cloud_agent.js";
import type * as http_routes_cloud_apps from "../http_routes/cloud_apps.js";
import type * as http_routes_cloud_drive from "../http_routes/cloud_drive.js";
import type * as http_routes_cloud_home from "../http_routes/cloud_home.js";
import type * as http_routes_cloud_integrations from "../http_routes/cloud_integrations.js";
import type * as http_routes_cloud_projects from "../http_routes/cloud_projects.js";
import type * as http_routes_desktop_releases from "../http_routes/desktop_releases.js";
import type * as http_routes_dictation from "../http_routes/dictation.js";
import type * as http_routes_gateway from "../http_routes/gateway.js";
import type * as http_routes_media from "../http_routes/media.js";
import type * as http_routes_mobile from "../http_routes/mobile.js";
import type * as http_routes_music from "../http_routes/music.js";
import type * as http_routes_native_oauth from "../http_routes/native_oauth.js";
import type * as http_routes_outbox from "../http_routes/outbox.js";
import type * as http_routes_stella_models from "../http_routes/stella_models.js";
import type * as http_routes_stripe from "../http_routes/stripe.js";
import type * as http_routes_synthesis from "../http_routes/synthesis.js";
import type * as http_routes_voice from "../http_routes/voice.js";
import type * as http_routes_x from "../http_routes/x.js";
import type * as http_routes_x_bot from "../http_routes/x_bot.js";
import type * as http_shared_admin from "../http_shared/admin.js";
import type * as http_shared_anon_device from "../http_shared/anon_device.js";
import type * as http_shared_assistant_text_frames from "../http_shared/assistant_text_frames.js";
import type * as http_shared_auth from "../http_shared/auth.js";
import type * as http_shared_better_auth_response from "../http_shared/better_auth_response.js";
import type * as http_shared_bounded_request_body from "../http_shared/bounded_request_body.js";
import type * as http_shared_capability from "../http_shared/capability.js";
import type * as http_shared_cors from "../http_shared/cors.js";
import type * as http_shared_request from "../http_shared/request.js";
import type * as http_shared_sse from "../http_shared/sse.js";
import type * as http_shared_test_accounts from "../http_shared/test_accounts.js";
import type * as http_shared_webhook_controls from "../http_shared/webhook_controls.js";
import type * as http_shared_xai_realtime from "../http_shared/xai_realtime.js";
import type * as lib_agent_constants from "../lib/agent_constants.js";
import type * as lib_alerts from "../lib/alerts.js";
import type * as lib_anonymous_usage from "../lib/anonymous_usage.js";
import type * as lib_app_integrity from "../lib/app_integrity.js";
import type * as lib_app_sdk_session from "../lib/app_sdk_session.js";
import type * as lib_app_session_tokens from "../lib/app_session_tokens.js";
import type * as lib_artifact_quota from "../lib/artifact_quota.js";
import type * as lib_async from "../lib/async.js";
import type * as lib_auth_ip_rate_limit from "../lib/auth_ip_rate_limit.js";
import type * as lib_auth_migration_paths from "../lib/auth_migration_paths.js";
import type * as lib_billing_date from "../lib/billing_date.js";
import type * as lib_billing_deletion from "../lib/billing_deletion.js";
import type * as lib_billing_money from "../lib/billing_money.js";
import type * as lib_billing_plans from "../lib/billing_plans.js";
import type * as lib_browser_auth_callback from "../lib/browser_auth_callback.js";
import type * as lib_builder_turns from "../lib/builder_turns.js";
import type * as lib_canvas_share_url from "../lib/canvas_share_url.js";
import type * as lib_capability_signing from "../lib/capability_signing.js";
import type * as lib_capability_verify from "../lib/capability_verify.js";
import type * as lib_chat_attachments from "../lib/chat_attachments.js";
import type * as lib_cloud_build_callback from "../lib/cloud_build_callback.js";
import type * as lib_cloud_drive_replacement from "../lib/cloud_drive_replacement.js";
import type * as lib_cloud_execution from "../lib/cloud_execution.js";
import type * as lib_cloud_home_context_updates from "../lib/cloud_home_context_updates.js";
import type * as lib_cloud_home_policy from "../lib/cloud_home_policy.js";
import type * as lib_coerce from "../lib/coerce.js";
import type * as lib_component_r2_deletion from "../lib/component_r2_deletion.js";
import type * as lib_composio_identity from "../lib/composio_identity.js";
import type * as lib_computer_agent_thread from "../lib/computer_agent_thread.js";
import type * as lib_content_tags from "../lib/content_tags.js";
import type * as lib_context_window from "../lib/context_window.js";
import type * as lib_crypto_utils from "../lib/crypto_utils.js";
import type * as lib_dev_apps_host_origin from "../lib/dev_apps_host_origin.js";
import type * as lib_disposable_email_domains from "../lib/disposable_email_domains.js";
import type * as lib_durable_fal_image_job from "../lib/durable_fal_image_job.js";
import type * as lib_email_i18n from "../lib/email_i18n.js";
import type * as lib_email_templates from "../lib/email_templates.js";
import type * as lib_error_classification from "../lib/error_classification.js";
import type * as lib_expo_oauth_proxy from "../lib/expo_oauth_proxy.js";
import type * as lib_gate_and_meter from "../lib/gate_and_meter.js";
import type * as lib_google_ads_mutations from "../lib/google_ads_mutations.js";
import type * as lib_handoff_crypto from "../lib/handoff_crypto.js";
import type * as lib_http_utils from "../lib/http_utils.js";
import type * as lib_identity_level from "../lib/identity_level.js";
import type * as lib_json from "../lib/json.js";
import type * as lib_managed_billing from "../lib/managed_billing.js";
import type * as lib_managed_dispatch from "../lib/managed_dispatch.js";
import type * as lib_managed_gateway from "../lib/managed_gateway.js";
import type * as lib_managed_usage from "../lib/managed_usage.js";
import type * as lib_managed_usage_reservation from "../lib/managed_usage_reservation.js";
import type * as lib_media_provider_dispatch from "../lib/media_provider_dispatch.js";
import type * as lib_memory_policy_change from "../lib/memory_policy_change.js";
import type * as lib_mobile_auth_link from "../lib/mobile_auth_link.js";
import type * as lib_models_dev from "../lib/models_dev.js";
import type * as lib_native_integration_limits from "../lib/native_integration_limits.js";
import type * as lib_native_ott_redirect from "../lib/native_ott_redirect.js";
import type * as lib_number_utils from "../lib/number_utils.js";
import type * as lib_object_utils from "../lib/object_utils.js";
import type * as lib_outbox_events from "../lib/outbox_events.js";
import type * as lib_owner_ids from "../lib/owner_ids.js";
import type * as lib_owner_migration_purge from "../lib/owner_migration_purge.js";
import type * as lib_owner_snapshot_notify from "../lib/owner_snapshot_notify.js";
import type * as lib_provider_keys from "../lib/provider_keys.js";
import type * as lib_provider_redaction from "../lib/provider_redaction.js";
import type * as lib_providers from "../lib/providers.js";
import type * as lib_r2_sigv4 from "../lib/r2_sigv4.js";
import type * as lib_rate_limits from "../lib/rate_limits.js";
import type * as lib_raw_r2_media_target from "../lib/raw_r2_media_target.js";
import type * as lib_redaction from "../lib/redaction.js";
import type * as lib_remote_turn_attempt_guard from "../lib/remote_turn_attempt_guard.js";
import type * as lib_retry_fetch from "../lib/retry_fetch.js";
import type * as lib_risk from "../lib/risk.js";
import type * as lib_session_identity from "../lib/session_identity.js";
import type * as lib_shopify_ucp from "../lib/shopify_ucp.js";
import type * as lib_stripe_operation_integrity from "../lib/stripe_operation_integrity.js";
import type * as lib_sybil from "../lib/sybil.js";
import type * as lib_telemetry_metric from "../lib/telemetry_metric.js";
import type * as lib_text_utils from "../lib/text_utils.js";
import type * as lib_tool_call_utils from "../lib/tool_call_utils.js";
import type * as lib_tts_dispatch_guard from "../lib/tts_dispatch_guard.js";
import type * as lib_turnstile from "../lib/turnstile.js";
import type * as lib_url_security from "../lib/url_security.js";
import type * as lib_validator from "../lib/validator.js";
import type * as lib_voice_authority from "../lib/voice_authority.js";
import type * as lib_voice_dispatch_guard from "../lib/voice_dispatch_guard.js";
import type * as lib_x_bot from "../lib/x_bot.js";
import type * as lib_x_bot_card from "../lib/x_bot_card.js";
import type * as lib_x_bot_logo from "../lib/x_bot_logo.js";
import type * as lib_x_bot_oauth from "../lib/x_bot_oauth.js";
import type * as lib_x_oauth from "../lib/x_oauth.js";
import type * as local_agent_threads from "../local_agent_threads.js";
import type * as media_billing from "../media_billing.js";
import type * as media_catalog from "../media_catalog.js";
import type * as media_contract from "../media_contract.js";
import type * as media_fal_webhooks from "../media_fal_webhooks.js";
import type * as media_image_limits from "../media_image_limits.js";
import type * as media_image_submission from "../media_image_submission.js";
import type * as media_jobs from "../media_jobs.js";
import type * as media_lyria from "../media_lyria.js";
import type * as media_openrouter_stt from "../media_openrouter_stt.js";
import type * as mobile_access from "../mobile_access.js";
import type * as mobile_auth from "../mobile_auth.js";
import type * as mobile_bridge from "../mobile_bridge.js";
import type * as mobile_push from "../mobile_push.js";
import type * as node_native_integration_schemas from "../node/native_integration_schemas.js";
import type * as owner_daily_counters from "../owner_daily_counters.js";
import type * as owner_enforcement from "../owner_enforcement.js";
import type * as owner_lifecycle from "../owner_lifecycle.js";
import type * as owner_origins from "../owner_origins.js";
import type * as owner_snapshot from "../owner_snapshot.js";
import type * as prompts_discovery_facts from "../prompts/discovery_facts.js";
import type * as prompts_execution from "../prompts/execution.js";
import type * as prompts_index from "../prompts/index.js";
import type * as prompts_invoke from "../prompts/invoke.js";
import type * as prompts_offline_responder from "../prompts/offline_responder.js";
import type * as prompts_registry from "../prompts/registry.js";
import type * as prompts_synthesis from "../prompts/synthesis.js";
import type * as prompts_system_assembly from "../prompts/system_assembly.js";
import type * as r2_files from "../r2_files.js";
import type * as rate_limits from "../rate_limits.js";
import type * as reset from "../reset.js";
import type * as risk from "../risk.js";
import type * as runtime_ai_anthropic from "../runtime_ai/anthropic.js";
import type * as runtime_ai_event_stream from "../runtime_ai/event_stream.js";
import type * as runtime_ai_google from "../runtime_ai/google.js";
import type * as runtime_ai_headers from "../runtime_ai/headers.js";
import type * as runtime_ai_json_parse from "../runtime_ai/json_parse.js";
import type * as runtime_ai_managed from "../runtime_ai/managed.js";
import type * as runtime_ai_model_utils from "../runtime_ai/model_utils.js";
import type * as runtime_ai_openai_completions from "../runtime_ai/openai_completions.js";
import type * as runtime_ai_openai_responses from "../runtime_ai/openai_responses.js";
import type * as runtime_ai_openai_responses_shared from "../runtime_ai/openai_responses_shared.js";
import type * as runtime_ai_retry from "../runtime_ai/retry.js";
import type * as runtime_ai_sanitize_unicode from "../runtime_ai/sanitize_unicode.js";
import type * as runtime_ai_simple_options from "../runtime_ai/simple_options.js";
import type * as runtime_ai_stream from "../runtime_ai/stream.js";
import type * as runtime_ai_tool_schema from "../runtime_ai/tool_schema.js";
import type * as runtime_ai_transform_messages from "../runtime_ai/transform_messages.js";
import type * as runtime_ai_types from "../runtime_ai/types.js";
import type * as runtime_ai_usage from "../runtime_ai/usage.js";
import type * as scheduling_cron_jobs from "../scheduling/cron_jobs.js";
import type * as scheduling_desktop_handoff_policy from "../scheduling/desktop_handoff_policy.js";
import type * as schema_abuse from "../schema/abuse.js";
import type * as schema_account_external_media from "../schema/account_external_media.js";
import type * as schema_agents from "../schema/agents.js";
import type * as schema_auth from "../schema/auth.js";
import type * as schema_billing from "../schema/billing.js";
import type * as schema_canvas_shares from "../schema/canvas_shares.js";
import type * as schema_cloud_agent_home from "../schema/cloud_agent_home.js";
import type * as schema_cloud_apps from "../schema/cloud_apps.js";
import type * as schema_cloud_browser from "../schema/cloud_browser.js";
import type * as schema_cloud_conversation_edits from "../schema/cloud_conversation_edits.js";
import type * as schema_cloud_drive from "../schema/cloud_drive.js";
import type * as schema_cloud_engines from "../schema/cloud_engines.js";
import type * as schema_cloud_outbox from "../schema/cloud_outbox.js";
import type * as schema_cloud_projects from "../schema/cloud_projects.js";
import type * as schema_cloud_schedule from "../schema/cloud_schedule.js";
import type * as schema_conversations from "../schema/conversations.js";
import type * as schema_desktop_releases from "../schema/desktop_releases.js";
import type * as schema_devices from "../schema/devices.js";
import type * as schema_emoji_packs from "../schema/emoji_packs.js";
import type * as schema_execution_placement from "../schema/execution_placement.js";
import type * as schema_fashion from "../schema/fashion.js";
import type * as schema_feedback from "../schema/feedback.js";
import type * as schema_gateway from "../schema/gateway.js";
import type * as schema_integrations from "../schema/integrations.js";
import type * as schema_media from "../schema/media.js";
import type * as schema_owner_lifecycle from "../schema/owner_lifecycle.js";
import type * as schema_prompts from "../schema/prompts.js";
import type * as schema_scheduling from "../schema/scheduling.js";
import type * as schema_telemetry from "../schema/telemetry.js";
import type * as schema_users from "../schema/users.js";
import type * as schema_x_bot from "../schema/x_bot.js";
import type * as shared_validators from "../shared_validators.js";
import type * as stella_models from "../stella_models.js";
import type * as stella_prompt_contract from "../stella_prompt_contract.js";
import type * as stella_prompts from "../stella_prompts.js";
import type * as stella_prompts_http from "../stella_prompts_http.js";
import type * as stripe_operation_dispatch from "../stripe_operation_dispatch.js";
import type * as telemetry_retention from "../telemetry_retention.js";
import type * as tools_backend from "../tools/backend.js";
import type * as tools_index from "../tools/index.js";
import type * as tools_types from "../tools/types.js";
import type * as tools_voice_schemas from "../tools/voice_schemas.js";
import type * as tts_dispatch from "../tts_dispatch.js";
import type * as tts_hls from "../tts_hls.js";
import type * as tts_stream from "../tts_stream.js";
import type * as voice_dispatch from "../voice_dispatch.js";
import type * as x_bot from "../x_bot.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  account_billing_purge: typeof account_billing_purge;
  account_deletion: typeof account_deletion;
  account_external_media: typeof account_external_media;
  account_external_media_store: typeof account_external_media_store;
  account_tts_purge: typeof account_tts_purge;
  admin_deletes: typeof admin_deletes;
  "agent/agents": typeof agent_agents;
  "agent/hooks": typeof agent_hooks;
  "agent/invoke": typeof agent_invoke;
  "agent/local_runtime": typeof agent_local_runtime;
  "agent/model": typeof agent_model;
  "agent/model_execution": typeof agent_model_execution;
  "agent/model_failover": typeof agent_model_failover;
  "agent/model_resolver": typeof agent_model_resolver;
  "agent/prompt_builder": typeof agent_prompt_builder;
  "agent/tool_schemas": typeof agent_tool_schemas;
  agent_event_ownership: typeof agent_event_ownership;
  ai_proxy_data: typeof ai_proxy_data;
  alerts: typeof alerts;
  anon_cleanup: typeof anon_cleanup;
  app_integrity: typeof app_integrity;
  app_integrity_node: typeof app_integrity_node;
  auth: typeof auth;
  auth_account_deletion: typeof auth_account_deletion;
  auth_migration: typeof auth_migration;
  "automation/index": typeof automation_index;
  "automation/runner": typeof automation_runner;
  billing: typeof billing;
  billing_measurement: typeof billing_measurement;
  billing_migrations: typeof billing_migrations;
  capability_contract: typeof capability_contract;
  "channels/connector_delivery": typeof channels_connector_delivery;
  "channels/connector_media": typeof channels_connector_media;
  "channels/connector_media_types": typeof channels_connector_media_types;
  "channels/connector_privacy": typeof channels_connector_privacy;
  "channels/connector_turn_payloads": typeof channels_connector_turn_payloads;
  "channels/execution_policy": typeof channels_execution_policy;
  cloud_agent_dispatch: typeof cloud_agent_dispatch;
  cloud_agent_home: typeof cloud_agent_home;
  cloud_apps: typeof cloud_apps;
  cloud_browser: typeof cloud_browser;
  cloud_conversation_edits: typeof cloud_conversation_edits;
  cloud_drive: typeof cloud_drive;
  cloud_drive_node: typeof cloud_drive_node;
  cloud_engines: typeof cloud_engines;
  cloud_home_context: typeof cloud_home_context;
  cloud_integration_catalog: typeof cloud_integration_catalog;
  cloud_memory: typeof cloud_memory;
  cloud_memory_lifecycle: typeof cloud_memory_lifecycle;
  cloud_outbox: typeof cloud_outbox;
  cloud_projects: typeof cloud_projects;
  cloud_purge: typeof cloud_purge;
  cloud_schedule: typeof cloud_schedule;
  cloud_skills: typeof cloud_skills;
  cloudflare_tunnels: typeof cloudflare_tunnels;
  component_r2_deletion: typeof component_r2_deletion;
  composio_native_dispatch: typeof composio_native_dispatch;
  composio_purge: typeof composio_purge;
  composio_purge_store: typeof composio_purge_store;
  composio_session_cleanup: typeof composio_session_cleanup;
  composio_session_dispatch: typeof composio_session_dispatch;
  conversations: typeof conversations;
  crons: typeof crons;
  "data/asset_metadata": typeof data_asset_metadata;
  "data/attachments": typeof data_attachments;
  "data/canvas_shares": typeof data_canvas_shares;
  "data/canvas_shares_actions": typeof data_canvas_shares_actions;
  "data/desktop_releases": typeof data_desktop_releases;
  "data/emoji_pack_generation": typeof data_emoji_pack_generation;
  "data/emoji_pack_grid": typeof data_emoji_pack_grid;
  "data/emoji_pack_grid_constants": typeof data_emoji_pack_grid_constants;
  "data/emoji_pack_reference_images": typeof data_emoji_pack_reference_images;
  "data/emoji_pack_uploads": typeof data_emoji_pack_uploads;
  "data/emoji_packs": typeof data_emoji_packs;
  "data/fashion": typeof data_fashion;
  "data/integrations": typeof data_integrations;
  "data/preferences": typeof data_preferences;
  "data/secrets": typeof data_secrets;
  "data/secrets_crypto": typeof data_secrets_crypto;
  "data/secrets_rotation": typeof data_secrets_rotation;
  "data/threads": typeof data_threads;
  "data/x_bot": typeof data_x_bot;
  device_identity: typeof device_identity;
  dictation_sessions: typeof dictation_sessions;
  events: typeof events;
  execution_placement: typeof execution_placement;
  feedback: typeof feedback;
  gateway_capabilities: typeof gateway_capabilities;
  http: typeof http;
  "http_routes/admin": typeof http_routes_admin;
  "http_routes/app_integrity": typeof http_routes_app_integrity;
  "http_routes/apps_sdk": typeof http_routes_apps_sdk;
  "http_routes/cloud_agent": typeof http_routes_cloud_agent;
  "http_routes/cloud_apps": typeof http_routes_cloud_apps;
  "http_routes/cloud_drive": typeof http_routes_cloud_drive;
  "http_routes/cloud_home": typeof http_routes_cloud_home;
  "http_routes/cloud_integrations": typeof http_routes_cloud_integrations;
  "http_routes/cloud_projects": typeof http_routes_cloud_projects;
  "http_routes/desktop_releases": typeof http_routes_desktop_releases;
  "http_routes/dictation": typeof http_routes_dictation;
  "http_routes/gateway": typeof http_routes_gateway;
  "http_routes/media": typeof http_routes_media;
  "http_routes/mobile": typeof http_routes_mobile;
  "http_routes/music": typeof http_routes_music;
  "http_routes/native_oauth": typeof http_routes_native_oauth;
  "http_routes/outbox": typeof http_routes_outbox;
  "http_routes/stella_models": typeof http_routes_stella_models;
  "http_routes/stripe": typeof http_routes_stripe;
  "http_routes/synthesis": typeof http_routes_synthesis;
  "http_routes/voice": typeof http_routes_voice;
  "http_routes/x": typeof http_routes_x;
  "http_routes/x_bot": typeof http_routes_x_bot;
  "http_shared/admin": typeof http_shared_admin;
  "http_shared/anon_device": typeof http_shared_anon_device;
  "http_shared/assistant_text_frames": typeof http_shared_assistant_text_frames;
  "http_shared/auth": typeof http_shared_auth;
  "http_shared/better_auth_response": typeof http_shared_better_auth_response;
  "http_shared/bounded_request_body": typeof http_shared_bounded_request_body;
  "http_shared/capability": typeof http_shared_capability;
  "http_shared/cors": typeof http_shared_cors;
  "http_shared/request": typeof http_shared_request;
  "http_shared/sse": typeof http_shared_sse;
  "http_shared/test_accounts": typeof http_shared_test_accounts;
  "http_shared/webhook_controls": typeof http_shared_webhook_controls;
  "http_shared/xai_realtime": typeof http_shared_xai_realtime;
  "lib/agent_constants": typeof lib_agent_constants;
  "lib/alerts": typeof lib_alerts;
  "lib/anonymous_usage": typeof lib_anonymous_usage;
  "lib/app_integrity": typeof lib_app_integrity;
  "lib/app_sdk_session": typeof lib_app_sdk_session;
  "lib/app_session_tokens": typeof lib_app_session_tokens;
  "lib/artifact_quota": typeof lib_artifact_quota;
  "lib/async": typeof lib_async;
  "lib/auth_ip_rate_limit": typeof lib_auth_ip_rate_limit;
  "lib/auth_migration_paths": typeof lib_auth_migration_paths;
  "lib/billing_date": typeof lib_billing_date;
  "lib/billing_deletion": typeof lib_billing_deletion;
  "lib/billing_money": typeof lib_billing_money;
  "lib/billing_plans": typeof lib_billing_plans;
  "lib/browser_auth_callback": typeof lib_browser_auth_callback;
  "lib/builder_turns": typeof lib_builder_turns;
  "lib/canvas_share_url": typeof lib_canvas_share_url;
  "lib/capability_signing": typeof lib_capability_signing;
  "lib/capability_verify": typeof lib_capability_verify;
  "lib/chat_attachments": typeof lib_chat_attachments;
  "lib/cloud_build_callback": typeof lib_cloud_build_callback;
  "lib/cloud_drive_replacement": typeof lib_cloud_drive_replacement;
  "lib/cloud_execution": typeof lib_cloud_execution;
  "lib/cloud_home_context_updates": typeof lib_cloud_home_context_updates;
  "lib/cloud_home_policy": typeof lib_cloud_home_policy;
  "lib/coerce": typeof lib_coerce;
  "lib/component_r2_deletion": typeof lib_component_r2_deletion;
  "lib/composio_identity": typeof lib_composio_identity;
  "lib/computer_agent_thread": typeof lib_computer_agent_thread;
  "lib/content_tags": typeof lib_content_tags;
  "lib/context_window": typeof lib_context_window;
  "lib/crypto_utils": typeof lib_crypto_utils;
  "lib/dev_apps_host_origin": typeof lib_dev_apps_host_origin;
  "lib/disposable_email_domains": typeof lib_disposable_email_domains;
  "lib/durable_fal_image_job": typeof lib_durable_fal_image_job;
  "lib/email_i18n": typeof lib_email_i18n;
  "lib/email_templates": typeof lib_email_templates;
  "lib/error_classification": typeof lib_error_classification;
  "lib/expo_oauth_proxy": typeof lib_expo_oauth_proxy;
  "lib/gate_and_meter": typeof lib_gate_and_meter;
  "lib/google_ads_mutations": typeof lib_google_ads_mutations;
  "lib/handoff_crypto": typeof lib_handoff_crypto;
  "lib/http_utils": typeof lib_http_utils;
  "lib/identity_level": typeof lib_identity_level;
  "lib/json": typeof lib_json;
  "lib/managed_billing": typeof lib_managed_billing;
  "lib/managed_dispatch": typeof lib_managed_dispatch;
  "lib/managed_gateway": typeof lib_managed_gateway;
  "lib/managed_usage": typeof lib_managed_usage;
  "lib/managed_usage_reservation": typeof lib_managed_usage_reservation;
  "lib/media_provider_dispatch": typeof lib_media_provider_dispatch;
  "lib/memory_policy_change": typeof lib_memory_policy_change;
  "lib/mobile_auth_link": typeof lib_mobile_auth_link;
  "lib/models_dev": typeof lib_models_dev;
  "lib/native_integration_limits": typeof lib_native_integration_limits;
  "lib/native_ott_redirect": typeof lib_native_ott_redirect;
  "lib/number_utils": typeof lib_number_utils;
  "lib/object_utils": typeof lib_object_utils;
  "lib/outbox_events": typeof lib_outbox_events;
  "lib/owner_ids": typeof lib_owner_ids;
  "lib/owner_migration_purge": typeof lib_owner_migration_purge;
  "lib/owner_snapshot_notify": typeof lib_owner_snapshot_notify;
  "lib/provider_keys": typeof lib_provider_keys;
  "lib/provider_redaction": typeof lib_provider_redaction;
  "lib/providers": typeof lib_providers;
  "lib/r2_sigv4": typeof lib_r2_sigv4;
  "lib/rate_limits": typeof lib_rate_limits;
  "lib/raw_r2_media_target": typeof lib_raw_r2_media_target;
  "lib/redaction": typeof lib_redaction;
  "lib/remote_turn_attempt_guard": typeof lib_remote_turn_attempt_guard;
  "lib/retry_fetch": typeof lib_retry_fetch;
  "lib/risk": typeof lib_risk;
  "lib/session_identity": typeof lib_session_identity;
  "lib/shopify_ucp": typeof lib_shopify_ucp;
  "lib/stripe_operation_integrity": typeof lib_stripe_operation_integrity;
  "lib/sybil": typeof lib_sybil;
  "lib/telemetry_metric": typeof lib_telemetry_metric;
  "lib/text_utils": typeof lib_text_utils;
  "lib/tool_call_utils": typeof lib_tool_call_utils;
  "lib/tts_dispatch_guard": typeof lib_tts_dispatch_guard;
  "lib/turnstile": typeof lib_turnstile;
  "lib/url_security": typeof lib_url_security;
  "lib/validator": typeof lib_validator;
  "lib/voice_authority": typeof lib_voice_authority;
  "lib/voice_dispatch_guard": typeof lib_voice_dispatch_guard;
  "lib/x_bot": typeof lib_x_bot;
  "lib/x_bot_card": typeof lib_x_bot_card;
  "lib/x_bot_logo": typeof lib_x_bot_logo;
  "lib/x_bot_oauth": typeof lib_x_bot_oauth;
  "lib/x_oauth": typeof lib_x_oauth;
  local_agent_threads: typeof local_agent_threads;
  media_billing: typeof media_billing;
  media_catalog: typeof media_catalog;
  media_contract: typeof media_contract;
  media_fal_webhooks: typeof media_fal_webhooks;
  media_image_limits: typeof media_image_limits;
  media_image_submission: typeof media_image_submission;
  media_jobs: typeof media_jobs;
  media_lyria: typeof media_lyria;
  media_openrouter_stt: typeof media_openrouter_stt;
  mobile_access: typeof mobile_access;
  mobile_auth: typeof mobile_auth;
  mobile_bridge: typeof mobile_bridge;
  mobile_push: typeof mobile_push;
  "node/native_integration_schemas": typeof node_native_integration_schemas;
  owner_daily_counters: typeof owner_daily_counters;
  owner_enforcement: typeof owner_enforcement;
  owner_lifecycle: typeof owner_lifecycle;
  owner_origins: typeof owner_origins;
  owner_snapshot: typeof owner_snapshot;
  "prompts/discovery_facts": typeof prompts_discovery_facts;
  "prompts/execution": typeof prompts_execution;
  "prompts/index": typeof prompts_index;
  "prompts/invoke": typeof prompts_invoke;
  "prompts/offline_responder": typeof prompts_offline_responder;
  "prompts/registry": typeof prompts_registry;
  "prompts/synthesis": typeof prompts_synthesis;
  "prompts/system_assembly": typeof prompts_system_assembly;
  r2_files: typeof r2_files;
  rate_limits: typeof rate_limits;
  reset: typeof reset;
  risk: typeof risk;
  "runtime_ai/anthropic": typeof runtime_ai_anthropic;
  "runtime_ai/event_stream": typeof runtime_ai_event_stream;
  "runtime_ai/google": typeof runtime_ai_google;
  "runtime_ai/headers": typeof runtime_ai_headers;
  "runtime_ai/json_parse": typeof runtime_ai_json_parse;
  "runtime_ai/managed": typeof runtime_ai_managed;
  "runtime_ai/model_utils": typeof runtime_ai_model_utils;
  "runtime_ai/openai_completions": typeof runtime_ai_openai_completions;
  "runtime_ai/openai_responses": typeof runtime_ai_openai_responses;
  "runtime_ai/openai_responses_shared": typeof runtime_ai_openai_responses_shared;
  "runtime_ai/retry": typeof runtime_ai_retry;
  "runtime_ai/sanitize_unicode": typeof runtime_ai_sanitize_unicode;
  "runtime_ai/simple_options": typeof runtime_ai_simple_options;
  "runtime_ai/stream": typeof runtime_ai_stream;
  "runtime_ai/tool_schema": typeof runtime_ai_tool_schema;
  "runtime_ai/transform_messages": typeof runtime_ai_transform_messages;
  "runtime_ai/types": typeof runtime_ai_types;
  "runtime_ai/usage": typeof runtime_ai_usage;
  "scheduling/cron_jobs": typeof scheduling_cron_jobs;
  "scheduling/desktop_handoff_policy": typeof scheduling_desktop_handoff_policy;
  "schema/abuse": typeof schema_abuse;
  "schema/account_external_media": typeof schema_account_external_media;
  "schema/agents": typeof schema_agents;
  "schema/auth": typeof schema_auth;
  "schema/billing": typeof schema_billing;
  "schema/canvas_shares": typeof schema_canvas_shares;
  "schema/cloud_agent_home": typeof schema_cloud_agent_home;
  "schema/cloud_apps": typeof schema_cloud_apps;
  "schema/cloud_browser": typeof schema_cloud_browser;
  "schema/cloud_conversation_edits": typeof schema_cloud_conversation_edits;
  "schema/cloud_drive": typeof schema_cloud_drive;
  "schema/cloud_engines": typeof schema_cloud_engines;
  "schema/cloud_outbox": typeof schema_cloud_outbox;
  "schema/cloud_projects": typeof schema_cloud_projects;
  "schema/cloud_schedule": typeof schema_cloud_schedule;
  "schema/conversations": typeof schema_conversations;
  "schema/desktop_releases": typeof schema_desktop_releases;
  "schema/devices": typeof schema_devices;
  "schema/emoji_packs": typeof schema_emoji_packs;
  "schema/execution_placement": typeof schema_execution_placement;
  "schema/fashion": typeof schema_fashion;
  "schema/feedback": typeof schema_feedback;
  "schema/gateway": typeof schema_gateway;
  "schema/integrations": typeof schema_integrations;
  "schema/media": typeof schema_media;
  "schema/owner_lifecycle": typeof schema_owner_lifecycle;
  "schema/prompts": typeof schema_prompts;
  "schema/scheduling": typeof schema_scheduling;
  "schema/telemetry": typeof schema_telemetry;
  "schema/users": typeof schema_users;
  "schema/x_bot": typeof schema_x_bot;
  shared_validators: typeof shared_validators;
  stella_models: typeof stella_models;
  stella_prompt_contract: typeof stella_prompt_contract;
  stella_prompts: typeof stella_prompts;
  stella_prompts_http: typeof stella_prompts_http;
  stripe_operation_dispatch: typeof stripe_operation_dispatch;
  telemetry_retention: typeof telemetry_retention;
  "tools/backend": typeof tools_backend;
  "tools/index": typeof tools_index;
  "tools/types": typeof tools_types;
  "tools/voice_schemas": typeof tools_voice_schemas;
  tts_dispatch: typeof tts_dispatch;
  tts_hls: typeof tts_hls;
  tts_stream: typeof tts_stream;
  voice_dispatch: typeof voice_dispatch;
  x_bot: typeof x_bot;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  r2: import("@convex-dev/r2/_generated/component.js").ComponentApi<"r2">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
