/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as account_deletion from "../account_deletion.js";
import type * as admin_deletes from "../admin_deletes.js";
import type * as agent_agents from "../agent/agents.js";
import type * as agent_hooks from "../agent/hooks.js";
import type * as agent_invoke from "../agent/invoke.js";
import type * as agent_local_runtime from "../agent/local_runtime.js";
import type * as agent_model from "../agent/model.js";
import type * as agent_model_execution from "../agent/model_execution.js";
import type * as agent_model_failover from "../agent/model_failover.js";
import type * as agent_model_resolver from "../agent/model_resolver.js";
import type * as agent_prompt_builder from "../agent/prompt_builder.js";
import type * as agent_tool_schemas from "../agent/tool_schemas.js";
import type * as agent_event_ownership from "../agent_event_ownership.js";
import type * as ai_proxy_data from "../ai_proxy_data.js";
import type * as alerts from "../alerts.js";
import type * as anon_cleanup from "../anon_cleanup.js";
import type * as app_integrity from "../app_integrity.js";
import type * as app_integrity_node from "../app_integrity_node.js";
import type * as auth from "../auth.js";
import type * as auth_account_deletion from "../auth_account_deletion.js";
import type * as auth_migration from "../auth_migration.js";
import type * as automation_index from "../automation/index.js";
import type * as automation_runner from "../automation/runner.js";
import type * as billing_bridge from "../billing_bridge.js";
import type * as channels_connector_delivery from "../channels/connector_delivery.js";
import type * as channels_connector_media_types from "../channels/connector_media_types.js";
import type * as channels_connector_privacy from "../channels/connector_privacy.js";
import type * as channels_connector_turn_payloads from "../channels/connector_turn_payloads.js";
import type * as channels_execution_policy from "../channels/execution_policy.js";
import type * as cloud_agent_dispatch from "../cloud_agent_dispatch.js";
import type * as cloud_apps from "../cloud_apps.js";
import type * as cloud_browser from "../cloud_browser.js";
import type * as cloud_connector_connect from "../cloud_connector_connect.js";
import type * as cloud_engines from "../cloud_engines.js";
import type * as cloud_integration_catalog from "../cloud_integration_catalog.js";
import type * as cloud_outbox from "../cloud_outbox.js";
import type * as cloud_projects from "../cloud_projects.js";
import type * as cloud_purge from "../cloud_purge.js";
import type * as composio_native_dispatch from "../composio_native_dispatch.js";
import type * as composio_purge from "../composio_purge.js";
import type * as composio_purge_store from "../composio_purge_store.js";
import type * as composio_session_cleanup from "../composio_session_cleanup.js";
import type * as composio_session_dispatch from "../composio_session_dispatch.js";
import type * as conversations from "../conversations.js";
import type * as crons from "../crons.js";
import type * as data_attachments from "../data/attachments.js";
import type * as data_canvas_shares from "../data/canvas_shares.js";
import type * as data_canvas_shares_actions from "../data/canvas_shares_actions.js";
import type * as data_desktop_releases from "../data/desktop_releases.js";
import type * as data_integrations from "../data/integrations.js";
import type * as data_secrets from "../data/secrets.js";
import type * as data_secrets_crypto from "../data/secrets_crypto.js";
import type * as data_secrets_rotation from "../data/secrets_rotation.js";
import type * as data_threads from "../data/threads.js";
import type * as data_x_bot from "../data/x_bot.js";
import type * as events from "../events.js";
import type * as gateway_capabilities from "../gateway_capabilities.js";
import type * as gateway_usage from "../gateway_usage.js";
import type * as http from "../http.js";
import type * as http_routes_admin from "../http_routes/admin.js";
import type * as http_routes_app_integrity from "../http_routes/app_integrity.js";
import type * as http_routes_auth_handoff from "../http_routes/auth_handoff.js";
import type * as http_routes_cloud_connector_connect from "../http_routes/cloud_connector_connect.js";
import type * as http_routes_cloud_integrations from "../http_routes/cloud_integrations.js";
import type * as http_routes_cloud_projects from "../http_routes/cloud_projects.js";
import type * as http_routes_desktop_releases from "../http_routes/desktop_releases.js";
import type * as http_routes_gateway from "../http_routes/gateway.js";
import type * as http_routes_native_oauth from "../http_routes/native_oauth.js";
import type * as http_routes_outbox from "../http_routes/outbox.js";
import type * as http_routes_stella_models from "../http_routes/stella_models.js";
import type * as http_routes_x from "../http_routes/x.js";
import type * as http_routes_x_bot from "../http_routes/x_bot.js";
import type * as http_shared_admin from "../http_shared/admin.js";
import type * as http_shared_anon_device from "../http_shared/anon_device.js";
import type * as http_shared_assistant_text_frames from "../http_shared/assistant_text_frames.js";
import type * as http_shared_auth from "../http_shared/auth.js";
import type * as http_shared_better_auth_response from "../http_shared/better_auth_response.js";
import type * as http_shared_bounded_request_body from "../http_shared/bounded_request_body.js";
import type * as http_shared_cloud_turn_caller from "../http_shared/cloud_turn_caller.js";
import type * as http_shared_cors from "../http_shared/cors.js";
import type * as http_shared_request from "../http_shared/request.js";
import type * as http_shared_sse from "../http_shared/sse.js";
import type * as http_shared_test_accounts from "../http_shared/test_accounts.js";
import type * as http_shared_webhook_controls from "../http_shared/webhook_controls.js";
import type * as lib_agent_constants from "../lib/agent_constants.js";
import type * as lib_alerts from "../lib/alerts.js";
import type * as lib_anonymous_usage from "../lib/anonymous_usage.js";
import type * as lib_app_integrity from "../lib/app_integrity.js";
import type * as lib_app_session_tokens from "../lib/app_session_tokens.js";
import type * as lib_artifact_quota from "../lib/artifact_quota.js";
import type * as lib_async from "../lib/async.js";
import type * as lib_auth_ip_rate_limit from "../lib/auth_ip_rate_limit.js";
import type * as lib_auth_migration_paths from "../lib/auth_migration_paths.js";
import type * as lib_billing_money from "../lib/billing_money.js";
import type * as lib_browser_auth_callback from "../lib/browser_auth_callback.js";
import type * as lib_builder_turns from "../lib/builder_turns.js";
import type * as lib_canvas_share_url from "../lib/canvas_share_url.js";
import type * as lib_capability_verify from "../lib/capability_verify.js";
import type * as lib_chat_attachments from "../lib/chat_attachments.js";
import type * as lib_cloud_build_callback from "../lib/cloud_build_callback.js";
import type * as lib_cloud_execution from "../lib/cloud_execution.js";
import type * as lib_coerce from "../lib/coerce.js";
import type * as lib_composio_identity from "../lib/composio_identity.js";
import type * as lib_computer_agent_thread from "../lib/computer_agent_thread.js";
import type * as lib_context_window from "../lib/context_window.js";
import type * as lib_crypto_utils from "../lib/crypto_utils.js";
import type * as lib_dev_apps_host_origin from "../lib/dev_apps_host_origin.js";
import type * as lib_disposable_email_domains from "../lib/disposable_email_domains.js";
import type * as lib_email_i18n from "../lib/email_i18n.js";
import type * as lib_email_templates from "../lib/email_templates.js";
import type * as lib_error_classification from "../lib/error_classification.js";
import type * as lib_expo_oauth_proxy from "../lib/expo_oauth_proxy.js";
import type * as lib_google_ads_mutations from "../lib/google_ads_mutations.js";
import type * as lib_handoff_crypto from "../lib/handoff_crypto.js";
import type * as lib_http_utils from "../lib/http_utils.js";
import type * as lib_identity_level from "../lib/identity_level.js";
import type * as lib_json from "../lib/json.js";
import type * as lib_managed_billing from "../lib/managed_billing.js";
import type * as lib_managed_dispatch from "../lib/managed_dispatch.js";
import type * as lib_managed_gateway from "../lib/managed_gateway.js";
import type * as lib_managed_usage from "../lib/managed_usage.js";
import type * as lib_mobile_auth_link from "../lib/mobile_auth_link.js";
import type * as lib_models_dev from "../lib/models_dev.js";
import type * as lib_native_integration_limits from "../lib/native_integration_limits.js";
import type * as lib_native_ott_redirect from "../lib/native_ott_redirect.js";
import type * as lib_number_utils from "../lib/number_utils.js";
import type * as lib_object_utils from "../lib/object_utils.js";
import type * as lib_outbox_events from "../lib/outbox_events.js";
import type * as lib_owner_ids from "../lib/owner_ids.js";
import type * as lib_owner_migration_purge from "../lib/owner_migration_purge.js";
import type * as lib_owner_plan from "../lib/owner_plan.js";
import type * as lib_owner_snapshot_notify from "../lib/owner_snapshot_notify.js";
import type * as lib_ownership_migration_status from "../lib/ownership_migration_status.js";
import type * as lib_provider_redaction from "../lib/provider_redaction.js";
import type * as lib_providers from "../lib/providers.js";
import type * as lib_r2_sigv4 from "../lib/r2_sigv4.js";
import type * as lib_rate_limits from "../lib/rate_limits.js";
import type * as lib_redaction from "../lib/redaction.js";
import type * as lib_remote_turn_attempt_guard from "../lib/remote_turn_attempt_guard.js";
import type * as lib_retry_fetch from "../lib/retry_fetch.js";
import type * as lib_risk from "../lib/risk.js";
import type * as lib_sybil from "../lib/sybil.js";
import type * as lib_telemetry_metric from "../lib/telemetry_metric.js";
import type * as lib_text_utils from "../lib/text_utils.js";
import type * as lib_tool_call_utils from "../lib/tool_call_utils.js";
import type * as lib_turnstile from "../lib/turnstile.js";
import type * as lib_url_security from "../lib/url_security.js";
import type * as lib_validator from "../lib/validator.js";
import type * as lib_x_bot from "../lib/x_bot.js";
import type * as lib_x_bot_card from "../lib/x_bot_card.js";
import type * as lib_x_bot_logo from "../lib/x_bot_logo.js";
import type * as lib_x_bot_oauth from "../lib/x_bot_oauth.js";
import type * as lib_x_oauth from "../lib/x_oauth.js";
import type * as mobile_auth from "../mobile_auth.js";
import type * as model_prices from "../model_prices.js";
import type * as node_native_integration_schemas from "../node/native_integration_schemas.js";
import type * as owner_daily_counters from "../owner_daily_counters.js";
import type * as owner_enforcement from "../owner_enforcement.js";
import type * as owner_lifecycle from "../owner_lifecycle.js";
import type * as owner_origins from "../owner_origins.js";
import type * as owner_snapshot from "../owner_snapshot.js";
import type * as prompts_discovery_facts from "../prompts/discovery_facts.js";
import type * as prompts_execution from "../prompts/execution.js";
import type * as prompts_index from "../prompts/index.js";
import type * as prompts_invoke from "../prompts/invoke.js";
import type * as prompts_offline_responder from "../prompts/offline_responder.js";
import type * as prompts_registry from "../prompts/registry.js";
import type * as prompts_system_assembly from "../prompts/system_assembly.js";
import type * as rate_limits from "../rate_limits.js";
import type * as reset from "../reset.js";
import type * as risk from "../risk.js";
import type * as runtime_ai_anthropic from "../runtime_ai/anthropic.js";
import type * as runtime_ai_event_stream from "../runtime_ai/event_stream.js";
import type * as runtime_ai_google from "../runtime_ai/google.js";
import type * as runtime_ai_headers from "../runtime_ai/headers.js";
import type * as runtime_ai_json_parse from "../runtime_ai/json_parse.js";
import type * as runtime_ai_managed from "../runtime_ai/managed.js";
import type * as runtime_ai_model_utils from "../runtime_ai/model_utils.js";
import type * as runtime_ai_openai_completions from "../runtime_ai/openai_completions.js";
import type * as runtime_ai_openai_responses from "../runtime_ai/openai_responses.js";
import type * as runtime_ai_openai_responses_shared from "../runtime_ai/openai_responses_shared.js";
import type * as runtime_ai_retry from "../runtime_ai/retry.js";
import type * as runtime_ai_sanitize_unicode from "../runtime_ai/sanitize_unicode.js";
import type * as runtime_ai_simple_options from "../runtime_ai/simple_options.js";
import type * as runtime_ai_stream from "../runtime_ai/stream.js";
import type * as runtime_ai_tool_schema from "../runtime_ai/tool_schema.js";
import type * as runtime_ai_transform_messages from "../runtime_ai/transform_messages.js";
import type * as runtime_ai_types from "../runtime_ai/types.js";
import type * as runtime_ai_usage from "../runtime_ai/usage.js";
import type * as scheduling_cron_jobs from "../scheduling/cron_jobs.js";
import type * as scheduling_desktop_handoff_policy from "../scheduling/desktop_handoff_policy.js";
import type * as schema_abuse from "../schema/abuse.js";
import type * as schema_agents from "../schema/agents.js";
import type * as schema_auth from "../schema/auth.js";
import type * as schema_billing from "../schema/billing.js";
import type * as schema_canvas_shares from "../schema/canvas_shares.js";
import type * as schema_cloud_apps from "../schema/cloud_apps.js";
import type * as schema_cloud_browser from "../schema/cloud_browser.js";
import type * as schema_cloud_connector_connect from "../schema/cloud_connector_connect.js";
import type * as schema_cloud_engines from "../schema/cloud_engines.js";
import type * as schema_cloud_outbox from "../schema/cloud_outbox.js";
import type * as schema_cloud_projects from "../schema/cloud_projects.js";
import type * as schema_conversations from "../schema/conversations.js";
import type * as schema_desktop_releases from "../schema/desktop_releases.js";
import type * as schema_devices from "../schema/devices.js";
import type * as schema_execution_placement from "../schema/execution_placement.js";
import type * as schema_gateway from "../schema/gateway.js";
import type * as schema_integrations from "../schema/integrations.js";
import type * as schema_owner_lifecycle from "../schema/owner_lifecycle.js";
import type * as schema_prompts from "../schema/prompts.js";
import type * as schema_telemetry from "../schema/telemetry.js";
import type * as schema_users from "../schema/users.js";
import type * as schema_x_bot from "../schema/x_bot.js";
import type * as shared_validators from "../shared_validators.js";
import type * as stella_models from "../stella_models.js";
import type * as stella_prompt_contract from "../stella_prompt_contract.js";
import type * as stella_prompts from "../stella_prompts.js";
import type * as stella_prompts_http from "../stella_prompts_http.js";
import type * as telemetry_retention from "../telemetry_retention.js";
import type * as tools_backend from "../tools/backend.js";
import type * as tools_index from "../tools/index.js";
import type * as tools_types from "../tools/types.js";
import type * as x_bot from "../x_bot.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  account_deletion: typeof account_deletion;
  admin_deletes: typeof admin_deletes;
  "agent/agents": typeof agent_agents;
  "agent/hooks": typeof agent_hooks;
  "agent/invoke": typeof agent_invoke;
  "agent/local_runtime": typeof agent_local_runtime;
  "agent/model": typeof agent_model;
  "agent/model_execution": typeof agent_model_execution;
  "agent/model_failover": typeof agent_model_failover;
  "agent/model_resolver": typeof agent_model_resolver;
  "agent/prompt_builder": typeof agent_prompt_builder;
  "agent/tool_schemas": typeof agent_tool_schemas;
  agent_event_ownership: typeof agent_event_ownership;
  ai_proxy_data: typeof ai_proxy_data;
  alerts: typeof alerts;
  anon_cleanup: typeof anon_cleanup;
  app_integrity: typeof app_integrity;
  app_integrity_node: typeof app_integrity_node;
  auth: typeof auth;
  auth_account_deletion: typeof auth_account_deletion;
  auth_migration: typeof auth_migration;
  "automation/index": typeof automation_index;
  "automation/runner": typeof automation_runner;
  billing_bridge: typeof billing_bridge;
  "channels/connector_delivery": typeof channels_connector_delivery;
  "channels/connector_media_types": typeof channels_connector_media_types;
  "channels/connector_privacy": typeof channels_connector_privacy;
  "channels/connector_turn_payloads": typeof channels_connector_turn_payloads;
  "channels/execution_policy": typeof channels_execution_policy;
  cloud_agent_dispatch: typeof cloud_agent_dispatch;
  cloud_apps: typeof cloud_apps;
  cloud_browser: typeof cloud_browser;
  cloud_connector_connect: typeof cloud_connector_connect;
  cloud_engines: typeof cloud_engines;
  cloud_integration_catalog: typeof cloud_integration_catalog;
  cloud_outbox: typeof cloud_outbox;
  cloud_projects: typeof cloud_projects;
  cloud_purge: typeof cloud_purge;
  composio_native_dispatch: typeof composio_native_dispatch;
  composio_purge: typeof composio_purge;
  composio_purge_store: typeof composio_purge_store;
  composio_session_cleanup: typeof composio_session_cleanup;
  composio_session_dispatch: typeof composio_session_dispatch;
  conversations: typeof conversations;
  crons: typeof crons;
  "data/attachments": typeof data_attachments;
  "data/canvas_shares": typeof data_canvas_shares;
  "data/canvas_shares_actions": typeof data_canvas_shares_actions;
  "data/desktop_releases": typeof data_desktop_releases;
  "data/integrations": typeof data_integrations;
  "data/secrets": typeof data_secrets;
  "data/secrets_crypto": typeof data_secrets_crypto;
  "data/secrets_rotation": typeof data_secrets_rotation;
  "data/threads": typeof data_threads;
  "data/x_bot": typeof data_x_bot;
  events: typeof events;
  gateway_capabilities: typeof gateway_capabilities;
  gateway_usage: typeof gateway_usage;
  http: typeof http;
  "http_routes/admin": typeof http_routes_admin;
  "http_routes/app_integrity": typeof http_routes_app_integrity;
  "http_routes/auth_handoff": typeof http_routes_auth_handoff;
  "http_routes/cloud_connector_connect": typeof http_routes_cloud_connector_connect;
  "http_routes/cloud_integrations": typeof http_routes_cloud_integrations;
  "http_routes/cloud_projects": typeof http_routes_cloud_projects;
  "http_routes/desktop_releases": typeof http_routes_desktop_releases;
  "http_routes/gateway": typeof http_routes_gateway;
  "http_routes/native_oauth": typeof http_routes_native_oauth;
  "http_routes/outbox": typeof http_routes_outbox;
  "http_routes/stella_models": typeof http_routes_stella_models;
  "http_routes/x": typeof http_routes_x;
  "http_routes/x_bot": typeof http_routes_x_bot;
  "http_shared/admin": typeof http_shared_admin;
  "http_shared/anon_device": typeof http_shared_anon_device;
  "http_shared/assistant_text_frames": typeof http_shared_assistant_text_frames;
  "http_shared/auth": typeof http_shared_auth;
  "http_shared/better_auth_response": typeof http_shared_better_auth_response;
  "http_shared/bounded_request_body": typeof http_shared_bounded_request_body;
  "http_shared/cloud_turn_caller": typeof http_shared_cloud_turn_caller;
  "http_shared/cors": typeof http_shared_cors;
  "http_shared/request": typeof http_shared_request;
  "http_shared/sse": typeof http_shared_sse;
  "http_shared/test_accounts": typeof http_shared_test_accounts;
  "http_shared/webhook_controls": typeof http_shared_webhook_controls;
  "lib/agent_constants": typeof lib_agent_constants;
  "lib/alerts": typeof lib_alerts;
  "lib/anonymous_usage": typeof lib_anonymous_usage;
  "lib/app_integrity": typeof lib_app_integrity;
  "lib/app_session_tokens": typeof lib_app_session_tokens;
  "lib/artifact_quota": typeof lib_artifact_quota;
  "lib/async": typeof lib_async;
  "lib/auth_ip_rate_limit": typeof lib_auth_ip_rate_limit;
  "lib/auth_migration_paths": typeof lib_auth_migration_paths;
  "lib/billing_money": typeof lib_billing_money;
  "lib/browser_auth_callback": typeof lib_browser_auth_callback;
  "lib/builder_turns": typeof lib_builder_turns;
  "lib/canvas_share_url": typeof lib_canvas_share_url;
  "lib/capability_verify": typeof lib_capability_verify;
  "lib/chat_attachments": typeof lib_chat_attachments;
  "lib/cloud_build_callback": typeof lib_cloud_build_callback;
  "lib/cloud_execution": typeof lib_cloud_execution;
  "lib/coerce": typeof lib_coerce;
  "lib/composio_identity": typeof lib_composio_identity;
  "lib/computer_agent_thread": typeof lib_computer_agent_thread;
  "lib/context_window": typeof lib_context_window;
  "lib/crypto_utils": typeof lib_crypto_utils;
  "lib/dev_apps_host_origin": typeof lib_dev_apps_host_origin;
  "lib/disposable_email_domains": typeof lib_disposable_email_domains;
  "lib/email_i18n": typeof lib_email_i18n;
  "lib/email_templates": typeof lib_email_templates;
  "lib/error_classification": typeof lib_error_classification;
  "lib/expo_oauth_proxy": typeof lib_expo_oauth_proxy;
  "lib/google_ads_mutations": typeof lib_google_ads_mutations;
  "lib/handoff_crypto": typeof lib_handoff_crypto;
  "lib/http_utils": typeof lib_http_utils;
  "lib/identity_level": typeof lib_identity_level;
  "lib/json": typeof lib_json;
  "lib/managed_billing": typeof lib_managed_billing;
  "lib/managed_dispatch": typeof lib_managed_dispatch;
  "lib/managed_gateway": typeof lib_managed_gateway;
  "lib/managed_usage": typeof lib_managed_usage;
  "lib/mobile_auth_link": typeof lib_mobile_auth_link;
  "lib/models_dev": typeof lib_models_dev;
  "lib/native_integration_limits": typeof lib_native_integration_limits;
  "lib/native_ott_redirect": typeof lib_native_ott_redirect;
  "lib/number_utils": typeof lib_number_utils;
  "lib/object_utils": typeof lib_object_utils;
  "lib/outbox_events": typeof lib_outbox_events;
  "lib/owner_ids": typeof lib_owner_ids;
  "lib/owner_migration_purge": typeof lib_owner_migration_purge;
  "lib/owner_plan": typeof lib_owner_plan;
  "lib/owner_snapshot_notify": typeof lib_owner_snapshot_notify;
  "lib/ownership_migration_status": typeof lib_ownership_migration_status;
  "lib/provider_redaction": typeof lib_provider_redaction;
  "lib/providers": typeof lib_providers;
  "lib/r2_sigv4": typeof lib_r2_sigv4;
  "lib/rate_limits": typeof lib_rate_limits;
  "lib/redaction": typeof lib_redaction;
  "lib/remote_turn_attempt_guard": typeof lib_remote_turn_attempt_guard;
  "lib/retry_fetch": typeof lib_retry_fetch;
  "lib/risk": typeof lib_risk;
  "lib/sybil": typeof lib_sybil;
  "lib/telemetry_metric": typeof lib_telemetry_metric;
  "lib/text_utils": typeof lib_text_utils;
  "lib/tool_call_utils": typeof lib_tool_call_utils;
  "lib/turnstile": typeof lib_turnstile;
  "lib/url_security": typeof lib_url_security;
  "lib/validator": typeof lib_validator;
  "lib/x_bot": typeof lib_x_bot;
  "lib/x_bot_card": typeof lib_x_bot_card;
  "lib/x_bot_logo": typeof lib_x_bot_logo;
  "lib/x_bot_oauth": typeof lib_x_bot_oauth;
  "lib/x_oauth": typeof lib_x_oauth;
  mobile_auth: typeof mobile_auth;
  model_prices: typeof model_prices;
  "node/native_integration_schemas": typeof node_native_integration_schemas;
  owner_daily_counters: typeof owner_daily_counters;
  owner_enforcement: typeof owner_enforcement;
  owner_lifecycle: typeof owner_lifecycle;
  owner_origins: typeof owner_origins;
  owner_snapshot: typeof owner_snapshot;
  "prompts/discovery_facts": typeof prompts_discovery_facts;
  "prompts/execution": typeof prompts_execution;
  "prompts/index": typeof prompts_index;
  "prompts/invoke": typeof prompts_invoke;
  "prompts/offline_responder": typeof prompts_offline_responder;
  "prompts/registry": typeof prompts_registry;
  "prompts/system_assembly": typeof prompts_system_assembly;
  rate_limits: typeof rate_limits;
  reset: typeof reset;
  risk: typeof risk;
  "runtime_ai/anthropic": typeof runtime_ai_anthropic;
  "runtime_ai/event_stream": typeof runtime_ai_event_stream;
  "runtime_ai/google": typeof runtime_ai_google;
  "runtime_ai/headers": typeof runtime_ai_headers;
  "runtime_ai/json_parse": typeof runtime_ai_json_parse;
  "runtime_ai/managed": typeof runtime_ai_managed;
  "runtime_ai/model_utils": typeof runtime_ai_model_utils;
  "runtime_ai/openai_completions": typeof runtime_ai_openai_completions;
  "runtime_ai/openai_responses": typeof runtime_ai_openai_responses;
  "runtime_ai/openai_responses_shared": typeof runtime_ai_openai_responses_shared;
  "runtime_ai/retry": typeof runtime_ai_retry;
  "runtime_ai/sanitize_unicode": typeof runtime_ai_sanitize_unicode;
  "runtime_ai/simple_options": typeof runtime_ai_simple_options;
  "runtime_ai/stream": typeof runtime_ai_stream;
  "runtime_ai/tool_schema": typeof runtime_ai_tool_schema;
  "runtime_ai/transform_messages": typeof runtime_ai_transform_messages;
  "runtime_ai/types": typeof runtime_ai_types;
  "runtime_ai/usage": typeof runtime_ai_usage;
  "scheduling/cron_jobs": typeof scheduling_cron_jobs;
  "scheduling/desktop_handoff_policy": typeof scheduling_desktop_handoff_policy;
  "schema/abuse": typeof schema_abuse;
  "schema/agents": typeof schema_agents;
  "schema/auth": typeof schema_auth;
  "schema/billing": typeof schema_billing;
  "schema/canvas_shares": typeof schema_canvas_shares;
  "schema/cloud_apps": typeof schema_cloud_apps;
  "schema/cloud_browser": typeof schema_cloud_browser;
  "schema/cloud_connector_connect": typeof schema_cloud_connector_connect;
  "schema/cloud_engines": typeof schema_cloud_engines;
  "schema/cloud_outbox": typeof schema_cloud_outbox;
  "schema/cloud_projects": typeof schema_cloud_projects;
  "schema/conversations": typeof schema_conversations;
  "schema/desktop_releases": typeof schema_desktop_releases;
  "schema/devices": typeof schema_devices;
  "schema/execution_placement": typeof schema_execution_placement;
  "schema/gateway": typeof schema_gateway;
  "schema/integrations": typeof schema_integrations;
  "schema/owner_lifecycle": typeof schema_owner_lifecycle;
  "schema/prompts": typeof schema_prompts;
  "schema/telemetry": typeof schema_telemetry;
  "schema/users": typeof schema_users;
  "schema/x_bot": typeof schema_x_bot;
  shared_validators: typeof shared_validators;
  stella_models: typeof stella_models;
  stella_prompt_contract: typeof stella_prompt_contract;
  stella_prompts: typeof stella_prompts;
  stella_prompts_http: typeof stella_prompts_http;
  telemetry_retention: typeof telemetry_retention;
  "tools/backend": typeof tools_backend;
  "tools/index": typeof tools_index;
  "tools/types": typeof tools_types;
  x_bot: typeof x_bot;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
