import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";

import {
  STELLA_PROMPT_MAX_CONTENT_BYTES,
  STELLA_PROMPT_MAX_TOTAL_CONTENT_BYTES,
} from "../convex/stella_prompt_contract";

const backendRoot = path.resolve(import.meta.dirname, "..");
const stellaRoot = path.resolve(backendRoot, "..", "stella");
const destinationRoot = path.join(backendRoot, "prompts", "stella-runtime");
const generatedPath = path.join(
  backendRoot,
  "convex",
  "stella_prompt_defaults.generated.ts",
);
const agentIds = [
  "orchestrator",
  "general",
  "schedule",
  "fashion",
  "social_session",
  "explore",
  "dream",
  "install_update",
] as const;
const promptIds = [
  "dream-scheduled",
  "chronicle-summarizer",
  "memory-review",
  "thread-compaction",
  "fallback-orchestrator",
  "fallback-subagent",
  "personality-stella",
  "personality-professional",
] as const;
const entries = [
  ...agentIds.map((id) => ({
    id: `agents/${id}.md`,
    kind: "agent" as const,
    source: path.join(
      stellaRoot,
      "runtime/extensions/stella-runtime/agents",
      `${id}.md`,
    ),
  })),
  ...promptIds.map((id) => ({
    id: `prompts/${id}.md`,
    kind: "prompt" as const,
    source: path.join(
      stellaRoot,
      "runtime/extensions/stella-runtime/prompts",
      `${id}.md`,
    ),
  })),
];

const sha256 = (value: string): string =>
  createHash("sha256").update(value).digest("hex");

const agentBody = (id: string, raw: string): string => {
  const frontmatter = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
  if (!frontmatter)
    throw new Error(`Agent ${id} is missing valid frontmatter.`);
  const body = raw.slice(frontmatter[0].length);
  if (!body.length) throw new Error(`Agent ${id} has an empty prompt body.`);
  return body;
};

const sourcePrompts = await Promise.all(
  entries.map(async (entry) => {
    const raw = await fs.readFile(entry.source, "utf-8");
    const content = entry.kind === "agent" ? agentBody(entry.id, raw) : raw;
    if (!content.length) throw new Error(`Prompt ${entry.id} is empty.`);
    const bytes = Buffer.byteLength(content, "utf-8");
    if (bytes > STELLA_PROMPT_MAX_CONTENT_BYTES) {
      throw new Error(`Prompt ${entry.id} exceeds the size limit.`);
    }
    return {
      id: entry.id,
      sha256: sha256(content),
      content,
      sourceRevision: "bundled-initial",
      updatedAt: 0,
    };
  }),
);
const totalBytes = sourcePrompts.reduce(
  (total, prompt) => total + Buffer.byteLength(prompt.content, "utf-8"),
  0,
);
if (totalBytes > STELLA_PROMPT_MAX_TOTAL_CONTENT_BYTES) {
  throw new Error("Canonical prompt content exceeds the total size limit.");
}
const prompts = [...sourcePrompts].sort((a, b) => a.id.localeCompare(b.id));
const revision = sha256(
  prompts.map((prompt) => `${prompt.id}:${prompt.sha256}`).join("\n"),
);
const generated = `/* Generated by scripts/sync-stella-prompt-defaults.ts. */\nexport const STELLA_PROMPT_DEFAULTS = ${JSON.stringify(
  { revision, publishedAt: 0, prompts },
  null,
  2,
)} as const;\n`;

const nonce = `${process.pid}-${Date.now()}`;
const stagingRoot = `${destinationRoot}.tmp-${nonce}`;
const destinationBackup = `${destinationRoot}.backup-${nonce}`;
const generatedTemp = `${generatedPath}.tmp-${nonce}`;
const generatedBackup = `${generatedPath}.backup-${nonce}`;
const exists = async (target: string): Promise<boolean> => {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
};

await fs.rm(stagingRoot, { recursive: true, force: true });
for (const prompt of prompts) {
  const destination = path.join(stagingRoot, prompt.id);
  await fs.mkdir(path.dirname(destination), { recursive: true });
  await fs.writeFile(destination, prompt.content, "utf-8");
}
await fs.writeFile(generatedTemp, generated, "utf-8");

let movedDestination = false;
let movedGenerated = false;
let installedDestination = false;
let installedGenerated = false;
try {
  if (await exists(destinationRoot)) {
    await fs.rename(destinationRoot, destinationBackup);
    movedDestination = true;
  }
  if (await exists(generatedPath)) {
    await fs.rename(generatedPath, generatedBackup);
    movedGenerated = true;
  }
  await fs.rename(stagingRoot, destinationRoot);
  installedDestination = true;
  await fs.rename(generatedTemp, generatedPath);
  installedGenerated = true;
} catch (error) {
  if (installedDestination) {
    await fs
      .rm(destinationRoot, { recursive: true, force: true })
      .catch(() => {});
  }
  if (installedGenerated) {
    await fs.rm(generatedPath, { force: true }).catch(() => {});
  }
  if (movedDestination) {
    await fs.rename(destinationBackup, destinationRoot).catch(() => {});
  }
  if (movedGenerated) {
    await fs.rename(generatedBackup, generatedPath).catch(() => {});
  }
  throw error;
} finally {
  await fs.rm(stagingRoot, { recursive: true, force: true }).catch(() => {});
  await fs.rm(generatedTemp, { force: true }).catch(() => {});
}
await fs
  .rm(destinationBackup, { recursive: true, force: true })
  .catch(() => {});
await fs.rm(generatedBackup, { force: true }).catch(() => {});

console.log(`Synced ${prompts.length} prompts at revision ${revision}.`);
