import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";

const backendRoot = path.resolve(import.meta.dirname, "..");
const stellaRoot = path.resolve(backendRoot, "..", "stella");
const destinationRoot = path.join(backendRoot, "prompts", "stella-runtime");
const generatedPath = path.join(
  backendRoot,
  "convex",
  "stella_prompt_defaults.generated.ts",
);
const entries = [
  ...[
    "orchestrator",
    "general",
    "schedule",
    "fashion",
    "social_session",
    "explore",
    "dream",
    "install_update",
  ].map((id) => ({
    id: `agents/${id}.md`,
    source: path.join(
      stellaRoot,
      "runtime/extensions/stella-runtime/agents",
      `${id}.md`,
    ),
  })),
  {
    id: "prompts/dream-scheduled.md",
    source: path.join(
      stellaRoot,
      "runtime/extensions/stella-runtime/prompts/dream-scheduled.md",
    ),
  },
];

await fs.rm(destinationRoot, { recursive: true, force: true });
const prompts = [];
for (const entry of entries) {
  const content = await fs.readFile(entry.source, "utf-8");
  const destination = path.join(destinationRoot, entry.id);
  await fs.mkdir(path.dirname(destination), { recursive: true });
  await fs.writeFile(destination, content, "utf-8");
  prompts.push({
    id: entry.id,
    sha256: createHash("sha256").update(content).digest("hex"),
    content,
    sourceRevision: "bundled-initial",
    updatedAt: 0,
  });
}
const revision = createHash("sha256")
  .update(prompts.map((prompt) => `${prompt.id}:${prompt.sha256}`).join("\n"))
  .digest("hex");
const generated = `/* Generated by scripts/sync-stella-prompt-defaults.ts. */\nexport const STELLA_PROMPT_DEFAULTS = ${JSON.stringify({ revision, prompts }, null, 2)} as const;\n`;
await fs.writeFile(generatedPath, generated, "utf-8");
console.log(`Synced ${prompts.length} prompts at revision ${revision}.`);
