import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";

import {
  STELLA_PROMPT_MAX_CONTENT_BYTES,
  STELLA_PROMPT_MAX_TOTAL_CONTENT_BYTES,
} from "../convex/stella_prompt_contract";

const backendRoot = path.resolve(import.meta.dirname, "..");
const sourceRoot = path.join(backendRoot, "prompts", "stella-runtime");
const generatedPath = path.join(
  backendRoot,
  "convex",
  "stella_prompt_defaults.generated.ts",
);
const agentIds = [
  "orchestrator",
  "general",
  "schedule",
  "fashion",
  "social_session",
  "explore",
  "dream",
  "install_update",
] as const;
const promptIds = [
  "dream-scheduled",
  "chronicle-summarizer",
  "memory-review",
  "thread-compaction",
  "fallback-orchestrator",
  "fallback-subagent",
  "personality-stella",
  "personality-professional",
] as const;
const entries = [
  ...agentIds.map((id) => ({
    id: `agents/${id}.md`,
    source: path.join(sourceRoot, "agents", `${id}.md`),
  })),
  ...promptIds.map((id) => ({
    id: `prompts/${id}.md`,
    source: path.join(sourceRoot, "prompts", `${id}.md`),
  })),
];

const sha256 = (value: string): string =>
  createHash("sha256").update(value).digest("hex");

const sourcePrompts = await Promise.all(
  entries.map(async (entry) => {
    const content = await fs.readFile(entry.source, "utf-8");
    if (!content.length) throw new Error(`Prompt ${entry.id} is empty.`);
    const bytes = Buffer.byteLength(content, "utf-8");
    if (bytes > STELLA_PROMPT_MAX_CONTENT_BYTES) {
      throw new Error(`Prompt ${entry.id} exceeds the size limit.`);
    }
    return {
      id: entry.id,
      sha256: sha256(content),
      content,
      sourceRevision: "backend-default",
      updatedAt: 0,
    };
  }),
);
const totalBytes = sourcePrompts.reduce(
  (total, prompt) => total + Buffer.byteLength(prompt.content, "utf-8"),
  0,
);
if (totalBytes > STELLA_PROMPT_MAX_TOTAL_CONTENT_BYTES) {
  throw new Error("Canonical prompt content exceeds the total size limit.");
}
const prompts = [...sourcePrompts].sort((a, b) => a.id.localeCompare(b.id));
const revision = sha256(
  prompts.map((prompt) => `${prompt.id}:${prompt.sha256}`).join("\n"),
);
const generated = `/* Generated by scripts/sync-stella-prompt-defaults.ts. */\nexport const STELLA_PROMPT_DEFAULTS = ${JSON.stringify(
  { revision, publishedAt: 0, prompts },
  null,
  2,
)} as const;\n`;

const generatedTemp = `${generatedPath}.tmp-${process.pid}-${Date.now()}`;
try {
  await fs.writeFile(generatedTemp, generated, "utf-8");
  await fs.rename(generatedTemp, generatedPath);
} catch (error) {
  await fs.rm(generatedTemp, { force: true }).catch(() => {});
  throw error;
}

console.log(`Synced ${prompts.length} prompts at revision ${revision}.`);
