import manifestJson from "./data/manifest.json";

/**
 * Bundled pet catalog — generated by `bun run scripts/fetch-pets.mjs`,
 * which mirrors the public Codex Pet Share into our R2 `stella-emotes`
 * bucket (the source of `spritesheetUrl`). The manifest sits in
 * `desktop/public/pets/manifest.json`; Vite resolves JSON imports
 * statically so changing the manifest invalidates the bundle, and the
 * desktop app never has to call the share API at runtime.
 *
 * Each entry is the minimum the picker page and overlay sprite renderer
 * need: stable id, display copy, sprite URL, and a kind/tags pair so we
 * can offer simple filtering without forking the share's UX.
 */
export type BuiltInPet = {
  id: string;
  displayName: string;
  description: string;
  kind: string;
  tags: string[];
  ownerName: string | null;
  spritesheetUrl: string;
  sourceUrl: string;
  /** Convenience alias used by older overlay code paths. */
  creator: string;
};

type RawPetManifest = {
  generatedAt?: string;
  publicBaseUrl?: string;
  bucket?: string;
  prefix?: string;
  count?: number;
  pets?: Array<Partial<BuiltInPet>>;
};

const manifest = manifestJson as RawPetManifest;

const normalize = (pet: Partial<BuiltInPet>): BuiltInPet | null => {
  if (!pet || typeof pet.id !== "string" || pet.id.length === 0) return null;
  const ownerName =
    typeof pet.ownerName === "string" && pet.ownerName.length > 0
      ? pet.ownerName
      : null;
  return {
    id: pet.id,
    displayName: pet.displayName?.trim() || pet.id,
    description: pet.description?.trim() ?? "",
    kind: pet.kind ?? "object",
    tags: Array.isArray(pet.tags) ? pet.tags.filter((t): t is string => typeof t === "string") : [],
    ownerName,
    spritesheetUrl: pet.spritesheetUrl ?? "",
    sourceUrl: pet.sourceUrl ?? "",
    creator: ownerName ?? "Codex Pet Share",
  };
};

export const BUILT_IN_PETS: BuiltInPet[] = (manifest.pets ?? [])
  .map(normalize)
  .filter((pet): pet is BuiltInPet => pet !== null && pet.spritesheetUrl !== "");

const PREFERRED_DEFAULT_IDS = ["codex", "stella", "duck", "dewey"];

const findDefault = (): BuiltInPet | undefined => {
  for (const id of PREFERRED_DEFAULT_IDS) {
    const match = BUILT_IN_PETS.find((pet) => pet.id === id);
    if (match) return match;
  }
  return BUILT_IN_PETS[0];
};

/** Stable id used when the user hasn't picked a pet yet. */
export const DEFAULT_PET_ID = findDefault()?.id ?? "codex";

/** Distinct tag set across the bundled catalog (sorted, dedup'd). */
export const PET_TAGS: string[] = (() => {
  const set = new Set<string>();
  for (const pet of BUILT_IN_PETS) {
    for (const tag of pet.tags) set.add(tag);
    set.add(pet.kind);
  }
  return Array.from(set).sort();
})();

const petById = new Map<string, BuiltInPet>(
  BUILT_IN_PETS.map((pet) => [pet.id, pet]),
);

export const findBuiltInPet = (id: string | null | undefined): BuiltInPet | undefined => {
  if (!id) return undefined;
  return petById.get(id);
};

/** Public URL of the R2 prefix the pets are uploaded to (informational). */
export const PETS_PUBLIC_BASE_URL: string = manifest.publicBaseUrl ?? "";
