/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d46a406e20abdb9fb841433898db43e3)
interface __BaseEnv_Env {
	ACTIVATION_PAGE_RATE_LIMITER: RateLimit;
	ACTIVATION_DECISION_RATE_LIMITER: RateLimit;
	PUBLIC_ORIGIN: "https://stella-v2-device-code-fixture-basic-nightingale-118.lolruuxi.workers.dev";
	DEVICE_AUTHORIZATIONS: DurableObjectNamespace<import("./src/index").DeviceAuthorizationSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DeviceAuthorizationSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN">> {}
}
