/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/store.lazy').then((d) => d.Route))
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/social.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/billing.lazy').then((d) => d.Route))
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/apps.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRoute,
} as any).lazy(() => import('./routes/apps.index.lazy').then((d) => d.Route))
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/c.$handle.lazy').then((d) => d.Route))
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/c/$handle': typeof CHandleRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/c/$handle': typeof CHandleRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/c/$handle': typeof CHandleRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/billing'
    | '/chat'
    | '/settings'
    | '/social'
    | '/store'
    | '/apps/$slug'
    | '/c/$handle'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/chat'
    | '/settings'
    | '/social'
    | '/store'
    | '/apps/$slug'
    | '/c/$handle'
    | '/apps'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/billing'
    | '/chat'
    | '/settings'
    | '/social'
    | '/store'
    | '/apps/$slug'
    | '/c/$handle'
    | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRouteWithChildren
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  StoreRoute: typeof StoreRoute
  CHandleRoute: typeof CHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof AppsRoute
    }
  }
}

interface AppsRouteChildren {
  AppsSlugRoute: typeof AppsSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsSlugRoute: AppsSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRouteWithChildren,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  StoreRoute: StoreRoute,
  CHandleRoute: CHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
